Config = Config or {}

--- Max baldų skaičius pagal būsto klasę
Config.FurnitureCaps = {
    economy = 12,
    standard = 20,
    premium = 32,
    luxury = 48,
    mansion = 72,
}

Config.Place = {
    maxDistance = 8.0,
    rotateStep = 15.0,
}

Config.Shop = {
    label = 'Baldų parduotuvė',
    pedModel = 's_m_m_autoshop_02',
    coords = vector4(46.65, -1749.62, 29.63, 50.0),
    blip = { sprite = 566, color = 5, scale = 0.8 },
    account = 'bank',
}

--- Katalogas: item = qb-inventory name (furn_*)
Config.Catalog = {
    chair_basic = {
        label = 'Medinė kėdė',
        category = 'chairs',
        categoryLabel = 'Kėdės',
        model = `prop_chair_02`,
        price = 450,
        interact = 'chair',
    },
    chair_office = {
        label = 'Biuro kėdė',
        category = 'chairs',
        categoryLabel = 'Kėdės',
        model = `prop_off_chair_01`,
        price = 900,
        interact = 'chair',
    },
    sofa_cheap = {
        label = 'Sofa (paprasta)',
        category = 'sofas',
        categoryLabel = 'Sofos',
        model = `prop_rub_couch01`,
        price = 1200,
        interact = 'sofa',
    },
    sofa_modern = {
        label = 'Sofa (moderni)',
        category = 'sofas',
        categoryLabel = 'Sofos',
        model = `v_res_mp_sofa`,
        price = 3500,
        interact = 'sofa',
    },
    table_small = {
        label = 'Mažas staliukas',
        category = 'tables',
        categoryLabel = 'Stalai',
        model = `prop_table_03`,
        price = 600,
        interact = 'none',
    },
    table_dining = {
        label = 'Valgomojo stalas',
        category = 'tables',
        categoryLabel = 'Stalai',
        model = `prop_table_04`,
        price = 1800,
        interact = 'none',
    },
    bed_single = {
        label = 'Viengulė lova',
        category = 'beds',
        categoryLabel = 'Lovos',
        model = `v_res_msonbed`,
        price = 2200,
        interact = 'bed',
    },
    bed_double = {
        label = 'Dvigulė lova',
        category = 'beds',
        categoryLabel = 'Lovos',
        model = `v_res_msonbed_s`,
        price = 4200,
        interact = 'bed',
    },
    tv_small = {
        label = 'Televizorius (mažas)',
        category = 'tvs',
        categoryLabel = 'Televizoriai',
        model = `prop_tv_flat_01`,
        price = 2800,
        interact = 'tv',
    },
    tv_large = {
        label = 'Televizorius (didelis)',
        category = 'tvs',
        categoryLabel = 'Televizoriai',
        model = `prop_tv_flat_03`,
        price = 5500,
        interact = 'tv',
    },
    wardrobe_basic = {
        label = 'Spinta',
        category = 'wardrobes',
        categoryLabel = 'Spintos',
        model = `v_res_tre_wardrobe`,
        price = 2500,
        interact = 'wardrobe',
    },
    safe_small = {
        label = 'Mažas seifas',
        category = 'safes',
        categoryLabel = 'Seifai',
        model = `prop_ld_int_safe_01`,
        price = 5000,
        interact = 'safe',
        stashSlots = 10,
        stashWeight = 50000,
    },
    safe_medium = {
        label = 'Vidutinis seifas',
        category = 'safes',
        categoryLabel = 'Seifai',
        model = `p_v_43_safe_s`,
        price = 12000,
        interact = 'safe',
        stashSlots = 24,
        stashWeight = 150000,
    },
    safe_large = {
        label = 'Didelis seifas',
        category = 'safes',
        categoryLabel = 'Seifai',
        model = `prop_ld_farm_safe01`,
        price = 28000,
        interact = 'safe',
        stashSlots = 48,
        stashWeight = 350000,
    },
    fridge = {
        label = 'Šaldytuvas',
        category = 'kitchen',
        categoryLabel = 'Virtuvė',
        model = `v_res_fridgemodsml`,
        price = 3200,
        interact = 'none',
    },
    sink = {
        label = 'Virtuvės kriauklė',
        category = 'kitchen',
        categoryLabel = 'Virtuvė',
        model = `prop_ff_sink_02`,
        price = 900,
        interact = 'none',
    },
    toilet = {
        label = 'Unitazas',
        category = 'bathroom',
        categoryLabel = 'Vonia',
        model = `prop_toilet_01`,
        price = 700,
        interact = 'none',
    },
    plant = {
        label = 'Augalas',
        category = 'decor',
        categoryLabel = 'Dekoras',
        model = `prop_plant_int_02a`,
        price = 350,
        interact = 'none',
    },
    lamp = {
        label = 'Lempa',
        category = 'decor',
        categoryLabel = 'Dekoras',
        model = `v_res_d_lampa`,
        price = 480,
        interact = 'none',
    },
    painting = {
        label = 'Paveikslas',
        category = 'decor',
        categoryLabel = 'Dekoras',
        model = `prop_painting_01`,
        price = 800,
        interact = 'none',
    },
}

--- Įrengto būsto pradiniai baldai (relative nuo interior.enter)
--- x,y,z, heading — relative offset + heading
Config.Presets = {
    economy = {
        { key = 'chair_basic', x = 1.2, y = 0.8, z = 0.0, h = 90.0 },
        { key = 'table_small', x = 0.4, y = 0.8, z = 0.0, h = 0.0 },
        { key = 'bed_single', x = -1.5, y = 2.0, z = 0.0, h = 180.0 },
    },
    standard = {
        { key = 'sofa_cheap', x = 1.5, y = 1.0, z = 0.0, h = 270.0 },
        { key = 'table_small', x = 0.5, y = 1.0, z = 0.0, h = 0.0 },
        { key = 'tv_small', x = -1.2, y = 1.0, z = 0.0, h = 90.0 },
        { key = 'bed_single', x = 2.0, y = -1.5, z = 0.0, h = 0.0 },
        { key = 'wardrobe_basic', x = -2.0, y = -1.0, z = 0.0, h = 90.0 },
        { key = 'chair_basic', x = 0.0, y = -0.5, z = 0.0, h = 180.0 },
    },
    premium = {
        { key = 'sofa_modern', x = 2.0, y = 1.5, z = 0.0, h = 200.0 },
        { key = 'table_dining', x = 0.0, y = 0.5, z = 0.0, h = 0.0 },
        { key = 'chair_office', x = 0.8, y = 0.5, z = 0.0, h = 90.0 },
        { key = 'tv_large', x = -2.0, y = 1.5, z = 0.0, h = 90.0 },
        { key = 'bed_double', x = 2.5, y = -2.0, z = 0.0, h = 0.0 },
        { key = 'wardrobe_basic', x = -2.5, y = -1.5, z = 0.0, h = 90.0 },
        { key = 'safe_small', x = -1.0, y = -2.0, z = 0.0, h = 0.0 },
        { key = 'lamp', x = 1.0, y = -2.0, z = 0.0, h = 0.0 },
        { key = 'plant', x = -0.5, y = 2.0, z = 0.0, h = 0.0 },
    },
    luxury = {
        { key = 'sofa_modern', x = 2.5, y = 2.0, z = 0.0, h = 180.0 },
        { key = 'sofa_modern', x = -2.5, y = 2.0, z = 0.0, h = 0.0 },
        { key = 'table_dining', x = 0.0, y = 1.0, z = 0.0, h = 0.0 },
        { key = 'tv_large', x = 0.0, y = 3.0, z = 0.0, h = 180.0 },
        { key = 'bed_double', x = 3.0, y = -2.5, z = 0.0, h = 90.0 },
        { key = 'wardrobe_basic', x = -3.0, y = -2.0, z = 0.0, h = 90.0 },
        { key = 'safe_medium', x = -2.0, y = -3.0, z = 0.0, h = 0.0 },
        { key = 'fridge', x = 2.0, y = -3.0, z = 0.0, h = 0.0 },
        { key = 'plant', x = 1.5, y = 2.5, z = 0.0, h = 0.0 },
        { key = 'lamp', x = -1.5, y = 2.5, z = 0.0, h = 0.0 },
        { key = 'painting', x = 0.0, y = -1.0, z = 1.2, h = 0.0 },
    },
    mansion_richman = {
        { key = 'sofa_modern', x = 3.0, y = 2.0, z = 0.0, h = 180.0 },
        { key = 'sofa_modern', x = -3.0, y = 2.0, z = 0.0, h = 0.0 },
        { key = 'table_dining', x = 0.0, y = 0.5, z = 0.0, h = 0.0 },
        { key = 'tv_large', x = 0.0, y = 4.0, z = 0.0, h = 180.0 },
        { key = 'bed_double', x = 4.0, y = -3.0, z = 0.0, h = 90.0 },
        { key = 'wardrobe_basic', x = -4.0, y = -2.5, z = 0.0, h = 90.0 },
        { key = 'safe_large', x = -3.0, y = -4.0, z = 0.0, h = 0.0 },
        { key = 'fridge', x = 3.0, y = -4.0, z = 0.0, h = 0.0 },
        { key = 'plant', x = 2.0, y = 3.0, z = 0.0, h = 0.0 },
        { key = 'lamp', x = -2.0, y = 3.0, z = 0.0, h = 0.0 },
    },
    mansion_vinewood = {
        { key = 'sofa_modern', x = 3.0, y = 2.0, z = 0.0, h = 180.0 },
        { key = 'table_dining', x = 0.0, y = 0.5, z = 0.0, h = 0.0 },
        { key = 'tv_large', x = 0.0, y = 4.0, z = 0.0, h = 180.0 },
        { key = 'bed_double', x = 4.0, y = -3.0, z = 0.0, h = 90.0 },
        { key = 'wardrobe_basic', x = -4.0, y = -2.5, z = 0.0, h = 90.0 },
        { key = 'safe_large', x = -3.0, y = -4.0, z = 0.0, h = 0.0 },
        { key = 'fridge', x = 3.0, y = -4.0, z = 0.0, h = 0.0 },
        { key = 'plant', x = 2.0, y = 3.0, z = 0.0, h = 0.0 },
    },
}
