--- Persistent QBCore admin: addpermission / grantadmin → license cfg + JSON (išlieka po RR).
local QBCore = exports['qb-core']:GetCoreObject()

local DATA_FILE = 'admins.json'
local admins = {}

local function projectRoot()
    local path = GetResourcePath(GetCurrentResourceName()) or ''
    path = path:gsub('\\', '/')
    local root = path:match('^(.*)/resources/%[local%]/mrp_spawnfix$')
    if not root then
        root = path:match('^(.*)/resources/.+/mrp_spawnfix$')
    end
    return root
end

local function cfgPath()
    local root = projectRoot()
    if not root then return nil end
    return root .. '/cfg/admins_persistent.cfg'
end

local function normalizeLevel(level)
    level = tostring(level or 'god'):lower()
    if level == 'god' or level == 'admin' or level == 'mod' then return level end
    return 'god'
end

local function stripPrefix(id, prefix)
    if not id then return nil end
    id = tostring(id)
    local p = prefix .. ':'
    if id:sub(1, #p) == p then return id:sub(#p + 1) end
    return id
end

local function playerIds(src)
    local out = { license = nil, fivem = nil, discord = nil }
    for i = 0, GetNumPlayerIdentifiers(src) - 1 do
        local id = GetPlayerIdentifier(src, i)
        if id then
            local typ, val = id:match('^([^:]+):(.+)$')
            if typ == 'license' then out.license = val end
            if typ == 'fivem' then out.fivem = val end
            if typ == 'discord' then out.discord = val end
        end
    end
    if not out.license then
        out.license = stripPrefix(QBCore.Functions.GetIdentifier(src, 'license'), 'license')
    end
    return out
end

local function loadAdmins()
    local raw = LoadResourceFile(GetCurrentResourceName(), DATA_FILE)
    if not raw or raw == '' then
        admins = {}
        return
    end
    local ok, decoded = pcall(json.decode, raw)
    if ok and type(decoded) == 'table' then
        admins = decoded
    else
        admins = {}
        print('^1[mrp_spawnfix]^0 Nepavyko nuskaityti admins.json')
    end
end

local function writeCfgFile()
    local path = cfgPath()
    if not path then
        print('^1[mrp_spawnfix]^0 Nerastas projekto root — cfg/admins_persistent.cfg neįrašytas')
        return false
    end

    local lines = {
        '# AUTO-GENERATED by mrp_spawnfix — needitink ranka (bus perrašyta).',
        '# Pildoma automatiškai: /addpermission, /grantadmin',
        '# Paleidžiama per: exec cfg/admins_persistent.cfg (server.cfg)',
        '',
    }

    local keys = {}
    for license in pairs(admins) do
        keys[#keys + 1] = license
    end
    table.sort(keys)

    for _, license in ipairs(keys) do
        local row = admins[license]
        if type(row) == 'table' then
            local level = normalizeLevel(row.level)
            local name = tostring(row.name or 'unknown'):gsub('[%c\r\n]', ' ')
            lines[#lines + 1] = ('# %s (%s)'):format(name, level)
            if level == 'god' then
                lines[#lines + 1] = ('add_principal identifier.license:%s qbcore.god'):format(license)
                lines[#lines + 1] = ('add_principal identifier.license:%s group.admin'):format(license)
            else
                lines[#lines + 1] = ('add_principal identifier.license:%s qbcore.%s'):format(license, level)
            end
            if row.fivem and tostring(row.fivem) ~= '' then
                if level == 'god' then
                    lines[#lines + 1] = ('add_principal identifier.fivem:%s qbcore.god'):format(row.fivem)
                else
                    lines[#lines + 1] = ('add_principal identifier.fivem:%s qbcore.%s'):format(row.fivem, level)
                end
            end
            lines[#lines + 1] = ''
        end
    end

    local fh, err = io.open(path, 'w')
    if not fh then
        print(('^1[mrp_spawnfix]^0 cfg rašymas nepavyko: %s (%s)'):format(path, tostring(err)))
        return false
    end
    fh:write(table.concat(lines, '\n'))
    fh:write('\n')
    fh:close()
    return true
end

local function saveAdmins()
    SaveResourceFile(GetCurrentResourceName(), DATA_FILE, json.encode(admins), -1)
    writeCfgFile()
end

local function applyPrincipalCommands(license, row, remove)
    if not license or type(row) ~= 'table' then return end
    local level = normalizeLevel(row.level)
    local op = remove and 'remove_principal' or 'add_principal'
    local function run(principal, group)
        ExecuteCommand(('%s %s %s'):format(op, principal, group))
    end

    local lic = ('identifier.license:%s'):format(license)
    if level == 'god' then
        run(lic, 'qbcore.god')
        run(lic, 'group.admin')
    else
        run(lic, 'qbcore.' .. level)
    end
    if row.fivem and tostring(row.fivem) ~= '' then
        local fivem = ('identifier.fivem:%s'):format(row.fivem)
        if level == 'god' then
            run(fivem, 'qbcore.god')
        else
            run(fivem, 'qbcore.' .. level)
        end
    end
end

local function applyAllFromStore()
    local n = 0
    for license, row in pairs(admins) do
        applyPrincipalCommands(license, row, false)
        n = n + 1
    end
    if n > 0 then
        print(('^2[mrp_spawnfix]^0 Užkrauta %d nuolatinių adminų (license)'):format(n))
    end
end

--- Išsaugo license → lygis į JSON + cfg/admins_persistent.cfg
local function persistGrant(src, level, opts)
    opts = opts or {}
    level = normalizeLevel(level)
    local ids = playerIds(src)
    if not ids.license or ids.license == '' then
        print(('^1[mrp_spawnfix]^0 Persist admin fail: nėra license (src=%s)'):format(tostring(src)))
        return false, nil
    end

    local prev = admins[ids.license]
    local same = prev
        and normalizeLevel(prev.level) == level
        and tostring(prev.fivem or '') == tostring(ids.fivem or '')

    admins[ids.license] = {
        level = level,
        fivem = ids.fivem,
        discord = ids.discord,
        name = GetPlayerName(src) or ('id:' .. tostring(src)),
        updatedAt = os.time(),
    }
    applyPrincipalCommands(ids.license, admins[ids.license], false)

    if not same then
        saveAdmins()
        if opts.notify ~= false then
            print(('^2[mrp_spawnfix]^0 Admin išsaugotas: license:%s → %s'):format(ids.license, level))
        end
    end
    return true, ids.license, not same
end

local function persistRevoke(src)
    local ids = playerIds(src)
    if not ids.license or not admins[ids.license] then
        return false
    end
    local row = admins[ids.license]
    applyPrincipalCommands(ids.license, row, true)
    admins[ids.license] = nil
    saveAdmins()
    print(('^3[mrp_spawnfix]^0 Admin pašalintas iš cfg: license:%s'):format(ids.license))
    return true
end

--- Tik SESIJOS sync (login) — NEPERRAŠOM cfg kiekvieną kartą, bet jei naujas — įrašom tyliai
local function persistFromSync(src, level)
    return persistGrant(src, level, { notify = false })
end

local origAddPermission = QBCore.Functions.AddPermission
local origRemovePermission = QBCore.Functions.RemovePermission

--- /addpermission ir kiti AddPermission kvietimai — automatiškai į cfg
function QBCore.Functions.AddPermission(source, permission)
    origAddPermission(source, permission)
    --- syncQBCoreAdmin taip pat kviečia AddPermission — cfg atnaujinamas tik jei naujas/pasikeitė
    persistFromSync(source, permission)
end

function QBCore.Functions.RemovePermission(source, permission)
    origRemovePermission(source, permission)
    persistRevoke(source)
end

exports('PersistAdminGrant', function(src, level)
    return persistGrant(src, level, { notify = true })
end)

exports('PersistAdminRevoke', function(src)
    return persistRevoke(src)
end)

exports('ReloadPersistentAdmins', function()
    loadAdmins()
    applyAllFromStore()
    writeCfgFile()
    return true
end)

AddEventHandler('onResourceStart', function(res)
    if res ~= GetCurrentResourceName() then return end
    loadAdmins()
    writeCfgFile()
    SetTimeout(500, applyAllFromStore)
end)

CreateThread(function()
    loadAdmins()
    writeCfgFile()
    Wait(1000)
    applyAllFromStore()
end)
