-- REH Rebadged Car Pack
-- shop='pdm' = Simion; shop='luxury' = Importu salonas (Config.ImportDealership)
-- Kainos: mrp_vehicle_perf kai UsePerformancePricing=true (cia fallback).
RehVehicleEntries = {
    { model = '08srt8', name = 'Jeep 08RT', brand = 'Jeep', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'anniselegygt', name = 'Annis Elegy GT', brand = 'Annis', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'annisr33', name = 'Annis R33', brand = 'Annis', price = 480000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'benefactorc63', name = 'C63EW206', brand = 'MERC2', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63gr', name = 'Benefactor C63 GR', brand = 'Benefactor', price = 520000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'benefactorc63m', name = 'Benefactor C63S', brand = 'Benefactor', price = 485000, category = 'sports', type = 'automobile', shop = 'luxury' }, -- NOTE: Civilian yft identical to mrpd27; grille may flash R/B on horn/E despite clean meta (sirenSettings=0).
    { model = 'mrpd27', name = 'MRPD 27 — C63S nežymėta', brand = 'Benefactor', price = 42000, category = 'emergency', type = 'automobile', shop = false },
    { model = 'benefactorcle53', name = 'Benefactor CLE 53', brand = 'Benefactor', price = 465000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'benefactore63', name = 'Benefactor E63 Wagon', brand = 'Benefactor', price = 495000, category = 'wagons', type = 'automobile', shop = 'luxury' },
    { model = 'benefactorg63', name = 'Benefactor G63', brand = 'Benefactor', price = 425000, category = 'suvs', type = 'automobile', shop = 'luxury' },
    { model = 'benefactorgle', name = 'Benefactor ELG', brand = 'Benefactor', price = 125000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorgls', name = 'BRABUS', brand = 'MER', price = 120000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorrange', name = 'Benefactor Range', brand = 'Benefactor', price = 340000, category = 'suvs', type = 'automobile', shop = 'luxury' },
    { model = 'benefactors600', name = 'Benefactor S600', brand = 'Benefactor', price = 425000, category = 'sedans', type = 'automobile', shop = 'luxury' },
    { model = 'benefactors600b', name = 'Benefactor S600 Brabus', brand = 'Benefactor', price = 465000, category = 'sedans', type = 'automobile', shop = 'luxury' },
    { model = 'benefactors63l', name = 'MercedesAMG', brand = 'S63Lux', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors65', name = 'Benefactor S65', brand = 'Benefactor', price = 245000, category = 'coupes', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors87', name = 'Benefactor S87', brand = 'Benefactor', price = 550000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'benefactorspur', name = 'FLYSPUR24', brand = 'BENFLY1', price = 320500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bfpologti', name = 'BF Weevil GTI', brand = 'BF', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadobuffalo', name = 'Bravado Buffalo', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadocharger08', name = 'Bravado Buffalo 08', brand = 'Bravado', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bravadocharger23', name = 'Bravado Charger 23', brand = 'Bravado', price = 285000, category = 'muscle', type = 'automobile', shop = 'luxury' },
    { model = 'bravadodaytona', name = 'Bravado Gauntlet Daytona', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemon', name = 'Bravado Gauntlet Demon', brand = 'Bravado', price = 520000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemonsc', name = 'Bravado Demons', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemonsc2', name = 'Bravado Demon SC2', brand = 'Bravado', price = 420000, category = 'muscle', type = 'automobile', shop = 'luxury' },
    { model = 'bravadomagnum', name = 'Bravado Magnum SRT', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadosrt392', name = 'Bravado Gauntlet SRT 392', brand = 'Bravado', price = 222000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bravadosuburban', name = 'Bravado Granger XL', brand = 'Bravado', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'bravadoz28', name = 'Bravado Gauntlet Z28', brand = 'Bravado', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'burgerfahrzeupassat', name = 'Passat V6', brand = 'burgerfahrzeupassat', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'canissrt8', name = 'Jeep ST8', brand = 'Jeep', price = 108500, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'caniswrangler', name = 'SEC Wrangler', brand = 'SEC', price = 55000, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'coilraiden', name = 'Coil Raiden', brand = 'Coil', price = 69500, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'coquettec6', name = 'Coquette C6', brand = 'Invetero', price = 520000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'coquettec8', name = 'Coquette C8', brand = 'Invetero', price = 720000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'coquettezl1', name = 'Coquette ZL1', brand = 'Invetero', price = 560000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'coquettezr1', name = 'Coquette ZR1', brand = 'Invetero', price = 880000, category = 'super', type = 'automobile', shop = 'luxury' },
    { model = 'declasseimpala', name = 'Chevrolet Impala', brand = 'Chevrolet', price = 202000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'dinkablista', name = 'Dinka Blista', brand = 'Dinka', price = 55000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'dinkabooga', name = 'Booga VSRT', brand = 'Dinka', price = 116000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'dinkacivic', name = 'Dinka Blista Hatchback', brand = 'Dinka', price = 125000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'dinkansx', name = 'Acura Dinka NSX', brand = 'Acura', price = 3000000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'dinkawhip', name = 'Dinka Whip', brand = 'Dinka', price = 388000, category = 'coupes', type = 'automobile', shop = 'luxury' },
    { model = 'grottibrioso', name = 'Grotti Brioso', brand = 'Grotti', price = 245000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'inveteroc7', name = 'Coquette C7', brand = 'Invetero', price = 480000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'inveterozr1', name = 'Coquette ZR1 Extreme', brand = 'Invetero', price = 1250000, category = 'super', type = 'automobile', shop = 'luxury' },
    { model = 'karimaxima', name = 'Karin Maxima', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinaltima', name = 'Karin Altima', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinascent', name = 'Karin Ascent', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karincamry', name = 'Karin Camry', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karincorolla', name = 'Karin Asterope Corolla', brand = 'Karin', price = 117500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karineclipse', name = 'Karin Eclipse', brand = 'Karin', price = 245000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'karinelantra', name = 'Karin Elantra', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karingenesis', name = 'Karin Genesis', brand = 'Karin', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karink5gt', name = 'Karin K5 GT', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinq50', name = 'Karin Q50', brand = 'Karin', price = 116000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinrav4', name = 'Karin RAV4 Hybrid', brand = 'Karin', price = 55000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'karinsedan', name = 'Karin Sedan', brand = 'Karin', price = 185000, category = 'sedans', type = 'automobile', shop = 'luxury' },
    { model = 'karinsorento', name = 'Karin Sorento', brand = 'Karin', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'karinstinger', name = 'Karin Stinger', brand = 'Karin', price = 320500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinsupra', name = 'Karin Supra MK5', brand = 'Karin', price = 320000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'obeyttrs', name = 'Obey TRS', brand = 'Obey', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ocelotintruder', name = 'Acura Integra Type R', brand = 'Acura', price = 125000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'ocelotvanquish', name = 'Ocelot Vanquish', brand = 'Aston Martin', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'overflodjesko', name = 'Overflod Entity J', brand = 'Overflod', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'overflodjesko2', name = 'Overflod Jesko', brand = 'Overflod', price = 2500000, category = 'super', type = 'automobile', shop = 'luxury' },
    { model = 'pegassiurus', name = 'Pegassi Urus', brand = 'Pegassi', price = 165000, category = 'suvs', type = 'automobile', shop = 'luxury' },
    { model = 'pfister911', name = 'Pfister 911', brand = 'Pfister', price = 580000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'progen600', name = 'Progen 600LT', brand = 'Progen', price = 1800000, category = 'super', type = 'automobile', shop = 'luxury' }, -- NOTE: Texture swap bugs when changing liveries/mods — leave for later.
    { model = 'progenartura', name = 'Progen Artura', brand = 'Progen', price = 1650000, category = 'super', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtg20', name = 'Ubermacht Oracle G20', brand = 'Ubermacht', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm3cs', name = 'Ubermacht M3 CS', brand = 'Ubermacht', price = 520000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtm4', name = 'Ubermacht M4', brand = 'Ubermacht', price = 495000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtm4gts', name = 'Ubermacht M4 GTS', brand = 'Ubermacht', price = 620000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtm4q', name = 'Ubermacht M4 Competition', brand = 'Ubermacht', price = 540000, category = 'sports', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtm5', name = 'Ubermacht M5 CS', brand = 'Ubermacht', price = 485000, category = 'sedans', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtsentinelk5', name = 'Sentinel K5', brand = 'Ubermacht', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtx6m', name = 'Ubermacht X6M', brand = 'Ubermacht', price = 345000, category = 'suvs', type = 'automobile', shop = 'luxury' },
    { model = 'ubermachtx7', name = 'Ubermacht X7', brand = 'Ubermacht', price = 365000, category = 'suvs', type = 'automobile', shop = 'luxury' },
    { model = 'vapiddurango', name = 'Vapid Durango', brand = 'Vapid', price = 185000, category = 'suvs', type = 'automobile', shop = 'luxury' }, -- NOTE: Street SUV: ~1520kg, maxVel~163, raised susp. Same VC_SUV as Sandking Dura but not the same car.
    { model = 'vapidfugitive', name = 'Vapid Fugitive', brand = 'Vapid', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'vapidhawk', name = 'Vapid Hawk', brand = 'Vapid', price = 245000, category = 'suvs', type = 'automobile', shop = 'luxury' },
    { model = 'vapidsandkingdura', name = 'Vapid Sandking Dura', brand = 'Vapid', price = 285000, category = 'suvs', type = 'automobile', shop = 'luxury' }, -- NOTE: Heavier Durango-bodied Sandking: ~2150kg, maxVel~212. Same VC_SUV class as vapiddurango.
    { model = 'vapidstanier', name = 'Vapid Stanier Special', brand = 'Vapid', price = 108500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'vapidtrx', name = 'Vapid Sandking TRX', brand = 'Vapid', price = 74500, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'vapidtrxc', name = 'Vapid TRX Custom', brand = 'Vapid', price = 285000, category = 'offroad', type = 'automobile', shop = 'luxury' },
}
