-- REH Rebadged Car Pack (auto-generated)
return {
    { model = '08srt8', name = '08srt8', brand = 'Jeep', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'anniselegygt', name = 'Annis Elegy GT', brand = 'Annis', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'annisr33', name = 'annisr33', brand = 'Import', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63', name = 'C63EW206', brand = 'MERC2', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63gr', name = 'benefactorc63gr', brand = 'benefactorc63gr', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63m', name = 'C63S', brand = 'IKX3', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorcle53', name = 'benefactorcle53', brand = 'MERCEDES', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactore63', name = 'Benefactor Schafter Wagon', brand = 'Benefactor', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorg63', name = 'g63exc', brand = 'SEC', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorgle', name = 'benefactorgle', brand = 'benefactorgle', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorgls', name = 'BRABUS', brand = 'MER', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorrange', name = 'benefactorrange', brand = 'benefactorrange', price = 850000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors600', name = 'benefactors600', brand = 'benefactors600', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors600b', name = 'benefactors600b', brand = 'benefactors600b', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors63l', name = 'MercedesAMG', brand = 'S63Lux', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors65', name = 'benefactors65', brand = 'benefactors65', price = 65000, category = 'coupes', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors87', name = 'benefactors87', brand = 'BMW', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorspur', name = 'FLYSPUR24', brand = 'BENFLY1', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bfpologti', name = 'BF Weevil GTI', brand = 'BF', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadobuffalo', name = 'Bravado Buffalo', brand = 'Bravado', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadocharger08', name = 'Bravado Buffalo 08', brand = 'Bravado', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bravadocharger23', name = 'bravadocharger23', brand = 'Dodge', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodaytona', name = 'Bravado Gauntlet Daytona', brand = 'Bravado', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemon', name = 'Bravado Gauntlet Demon', brand = 'Bravado', price = 85000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemonsc', name = 'bravadodemonsc', brand = 'dodge', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemonsc2', name = 'bravadodemonsc2', brand = 'Ford', price = 85000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'bravadomagnum', name = 'Bravado Magnum SRT', brand = 'Bravado', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadosrt392', name = 'Bravado Gauntlet SRT 392', brand = 'Bravado', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bravadosuburban', name = 'Bravado Granger XL', brand = 'Bravado', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'bravadoz28', name = 'Bravado Gauntlet Z28', brand = 'Bravado', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'burgerfahrzeupassat', name = 'Passat V6', brand = 'burgerfahrzeupassat', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'canissrt8', name = 'Canis SRT8', brand = 'Canis', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'caniswrangler', name = 'WRANGLER', brand = 'SEC', price = 55000, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'coilraiden', name = 'Coil Raiden', brand = 'Coil', price = 55000, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'coquettec6', name = 'coquettec6', brand = 'Ford', price = 35000, category = 'utility', type = 'automobile', shop = 'pdm' },
    { model = 'coquettec8', name = 'Coquette C8', brand = 'Invetero', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'coquettec8a', name = 'coquettec8a', brand = 'CHEVORLET', price = 850000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'coquettezl1', name = 'coquettezl1', brand = 'CHEVROLET', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'coquettezr1', name = 'CORVETZR1', brand = 'CHEVROLET', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'declasseimpala', name = 'declasseimpala', brand = 'CHEVROLET', price = 85000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'dinkablista', name = 'Dinka Blista', brand = 'Dinka', price = 18000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'dinkabooga', name = 'dinkabooga', brand = 'Ford', price = 35000, category = 'utility', type = 'automobile', shop = 'pdm' },
    { model = 'dinkacivic', name = 'Dinka Blista Hatchback', brand = 'Dinka', price = 18000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'dinkansx', name = 'dinkansx', brand = 'Acura', price = 3200000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'dinkawhip', name = 'dinkawhip', brand = 'BMW M8 Hycade', price = 65000, category = 'coupes', type = 'automobile', shop = 'pdm' },
    { model = 'grottibrioso', name = 'Grotti Brioso', brand = 'Grotti', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'inveteroc7', name = 'Invetero Coquette C7', brand = 'Invetero', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'inveterozr1', name = 'Invetero Coquette ZR1', brand = 'Invetero', price = 3500000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'karimaxima', name = 'Karin Maxima', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinaltima', name = 'Karin Altima', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinascent', name = 'Karin Ascent', brand = 'Karin', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'karincamry', name = 'Karin Camry', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karincorolla', name = 'Karin Asterope Corolla', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karineclipse', name = 'karineclipse', brand = 'Mitsubishi', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'karinelantra', name = 'Karin Elantra', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karingenesis', name = 'Karin Genesis', brand = 'Karin', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'karink5gt', name = 'Karin K5 GT', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinq50', name = 'Karin Q50', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinrav4', name = 'Karin RAV4 Hybrid', brand = 'Karin', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'karinsedan', name = 'karinsedan', brand = 'karinsedan', price = 850000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'karinsorento', name = 'Karin Sorento', brand = 'Karin', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'karinstinger', name = 'Karin Stinger', brand = 'Karin', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinsupra', name = 'karinsupra', brand = 'Ford', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'obeyttrs', name = 'obeyttrs', brand = 'obeyttrs', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ocelotintruder', name = 'integratyper', brand = 'acura', price = 18000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'ocelotvanquish', name = 'ocelotvanquish', brand = 'astonm', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'overflodjesko', name = 'Overflod Entity J', brand = 'Overflod', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'overflodjesko2', name = 'attackjesko', brand = 'SEC', price = 3800000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'pegassiurus', name = 'Pegassi Toros', brand = 'Pegassi', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'pfister911', name = 'Pfister Comet 911', brand = 'Pfister', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'progen600', name = 'progen600', brand = 'FIVEMCAR.COM', price = 3200000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'progenartura', name = 'Progen Emperor Artura', brand = 'Progen', price = 3400000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtg20', name = 'Ubermacht Oracle G20', brand = 'Ubermacht', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm3cs', name = 'ComplainsPatent', brand = 'BMW', price = 850000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm4', name = 'Ubermacht Sentinel M4', brand = 'Ubermacht', price = 850000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm4gts', name = 'ubermachtm4gts', brand = 'MercedesBenz', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm4q', name = 'ubermachtm4q', brand = 'MoDreCustoms', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm5', name = 'Ubermacht M5 CS', brand = 'Ubermacht', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtsentinelk5', name = 'Ubermacht Sentinel K5', brand = 'Ubermacht', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtx6m', name = '2022 x6mlarte', brand = 'Dodge', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtx7', name = 'X7M60I', brand = 'BMWX71', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapiddurango', name = 'Vapid Durango', brand = 'Import', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'vapidfugitive', name = 'Vapid Fugitive', brand = 'Vapid', price = 45000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'vapidhawk', name = 'vapidhawk', brand = 'MoDreCustoms', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapidsandkingdura', name = 'VapidSandkingDura', brand = 'Vapid', price = 75000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapidstanier', name = 'Vapid Stanier Special', brand = 'Vapid', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'vapidtrx', name = 'Vapid Sandking TRX', brand = 'Vapid', price = 55000, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'vapidtrxc', name = 'vapidtrxc', brand = 'Dodge', price = 150000, category = 'sports', type = 'automobile', shop = 'pdm' },
}
