-- REH Rebadged Car Pack (auto-generated)
-- Kainos sinchronizuotos su mrp_vehicle_perf (greitis + 0-100)
RehVehicleEntries = {
    { model = '08srt8', name = 'Jeep 08RT', brand = 'Jeep', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'anniselegygt', name = 'Annis Elegy GT', brand = 'Annis', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'annisr33', name = 'Import Annis R33', brand = 'Import', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63', name = 'C63EW206', brand = 'MERC2', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63gr', name = 'Karin Supa MK6', brand = 'Karin', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorc63m', name = 'C63S', brand = 'IKX3', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorcle53', name = 'Benefactor ELC 53', brand = 'Benefactor', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactore63', name = 'Benefactor Schafter Wagon', brand = 'Benefactor', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorg63', name = 'g63exc', brand = 'SEC', price = 124500, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorgle', name = 'Benefactor ELG', brand = 'Benefactor', price = 125000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorgls', name = 'BRABUS', brand = 'MER', price = 120000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorrange', name = 'Benefactor Range', brand = 'Benefactor', price = 340000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors600', name = 'Benefactor S600', brand = 'Benefactor', price = 245000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors600b', name = 'benefactors600b', brand = 'benefactors600b', price = 328500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors63l', name = 'MercedesAMG', brand = 'S63Lux', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors65', name = 'Benefactor S65', brand = 'Benefactor', price = 245000, category = 'coupes', type = 'automobile', shop = 'pdm' },
    { model = 'benefactors87', name = 'Benefactor S87', brand = 'Benefactor', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'benefactorspur', name = 'FLYSPUR24', brand = 'BENFLY1', price = 320500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bfpologti', name = 'BF Weevil GTI', brand = 'BF', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadobuffalo', name = 'Bravado Buffalo', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadocharger08', name = 'Bravado Buffalo 08', brand = 'Bravado', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bravadocharger23', name = 'Bravado Charger TRS', brand = 'Dodge', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodaytona', name = 'Bravado Gauntlet Daytona', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemon', name = 'Bravado Gauntlet Demon', brand = 'Bravado', price = 520000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemonsc', name = 'Bravado Demons', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadodemonsc2', name = 'Bravado Demon SC2', brand = 'Bravado', price = 520000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'bravadomagnum', name = 'Bravado Magnum SRT', brand = 'Bravado', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'bravadosrt392', name = 'Bravado Gauntlet SRT 392', brand = 'Bravado', price = 222000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'bravadosuburban', name = 'Bravado Granger XL', brand = 'Bravado', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'bravadoz28', name = 'Bravado Gauntlet Z28', brand = 'Bravado', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'burgerfahrzeupassat', name = 'Passat V6', brand = 'burgerfahrzeupassat', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'canissrt8', name = 'Jeep ST8', brand = 'Jeep', price = 108500, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'caniswrangler', name = 'SEC Wrangler', brand = 'SEC', price = 55000, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'coilraiden', name = 'Coil Raiden', brand = 'Coil', price = 69500, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'coquettec6', name = 'Invetero Coquette C6', brand = 'Invetero', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'coquettec8', name = 'Coquette C8', brand = 'Invetero', price = 848000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'coquettezl1', name = 'Invetero Coquette LZ1', brand = 'Invetero', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'coquettezr1', name = 'CORVETZR1', brand = 'CHEVROLET', price = 880000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'declasseimpala', name = 'Chevrolet Impala', brand = 'Chevrolet', price = 202000, category = 'muscle', type = 'automobile', shop = 'pdm' },
    { model = 'dinkablista', name = 'Dinka Blista', brand = 'Dinka', price = 55000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'dinkabooga', name = 'Booga VSRT', brand = 'Dinka', price = 116000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'dinkacivic', name = 'Dinka Blista Hatchback', brand = 'Dinka', price = 125000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'dinkansx', name = 'Acura Dinka NSX', brand = 'Acura', price = 3000000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'dinkawhip', name = 'dinkawhip', brand = 'BMW M8 Hycade', price = 388000, category = 'coupes', type = 'automobile', shop = 'pdm' },
    { model = 'grottibrioso', name = 'Grotti Brioso', brand = 'Grotti', price = 245000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'inveteroc7', name = 'Invetero Coquette C7', brand = 'Invetero', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'inveterozr1', name = 'Invetero Coquette ZR1', brand = 'Invetero', price = 3000000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'karimaxima', name = 'Karin Maxima', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinaltima', name = 'Karin Altima', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinascent', name = 'Karin Ascent', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karincamry', name = 'Karin Camry', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karincorolla', name = 'Karin Asterope Corolla', brand = 'Karin', price = 117500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karineclipse', name = 'Karin Eclipse', brand = 'Karin', price = 245000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'karinelantra', name = 'Karin Elantra', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karingenesis', name = 'Karin Genesis', brand = 'Karin', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karink5gt', name = 'Karin K5 GT', brand = 'Karin', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinq50', name = 'Karin Q50', brand = 'Karin', price = 116000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinrav4', name = 'Karin RAV4 Hybrid', brand = 'Karin', price = 55000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'karinsedan', name = 'Vapid Fugitive', brand = 'Vapid', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinsorento', name = 'Karin Sorento', brand = 'Karin', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'karinstinger', name = 'Karin Stinger', brand = 'Karin', price = 320500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'karinsupra', name = 'Karin Supa MK5', brand = 'Karin', price = 245000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'obeyttrs', name = 'Obey TRS', brand = 'Obey', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ocelotintruder', name = 'Acura Integra Type R', brand = 'Acura', price = 125000, category = 'compacts', type = 'automobile', shop = 'pdm' },
    { model = 'ocelotvanquish', name = 'Ocelot Vanquish', brand = 'Aston Martin', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'overflodjesko', name = 'Overflod Entity J', brand = 'Overflod', price = 94000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'overflodjesko2', name = 'SEC Attack Jesko', brand = 'SEC', price = 3000000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'pegassiurus', name = 'Pegassi Toros', brand = 'Pegassi', price = 98000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'pfister911', name = 'Pfister Comet 911', brand = 'Pfister', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'progen600', name = 'progen600', brand = 'FIVEMCAR.COM', price = 3000000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'progenartura', name = 'Progen Emperor Artura', brand = 'Progen', price = 3000000, category = 'super', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtg20', name = 'Ubermacht Oracle G20', brand = 'Ubermacht', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm3cs', name = 'Benefactor M3', brand = 'Benefactor', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm4', name = 'Ubermacht Sentinel M4', brand = 'Ubermacht', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm4gts', name = 'ubermachtm4gts', brand = 'MercedesBenz', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm4q', name = 'ubermachtm4q', brand = 'MoDreCustoms', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtm5', name = 'Ubermacht M5 CS', brand = 'Ubermacht', price = 520000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtsentinelk5', name = 'Sentinel K5', brand = 'Ubermacht', price = 125000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtx6m', name = 'Ubermacht X6M', brand = 'Ubermacht', price = 245000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'ubermachtx7', name = 'Ubermacht X7M', brand = 'Ubermacht', price = 125000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapiddurango', name = 'Vapid Durango', brand = 'Vapid', price = 125000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapidfugitive', name = 'Vapid Fugitive', brand = 'Vapid', price = 245000, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'vapidhawk', name = 'MoDre Customs Vapid Hawk', brand = 'MoDre Customs', price = 245000, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapidsandkingdura', name = 'Vapid Sandking Dura', brand = 'Vapid', price = 348500, category = 'suvs', type = 'automobile', shop = 'pdm' },
    { model = 'vapidstanier', name = 'Vapid Stanier Special', brand = 'Vapid', price = 108500, category = 'sedans', type = 'automobile', shop = 'pdm' },
    { model = 'vapidtrx', name = 'Vapid Sandking TRX', brand = 'Vapid', price = 74500, category = 'offroad', type = 'automobile', shop = 'pdm' },
    { model = 'vapidtrxc', name = 'vapidtrxc', brand = 'Dodge', price = 520000, category = 'sports', type = 'automobile', shop = 'pdm' },
}
