--- Turf progresija — misijos + graffiti + narkotikai + buvimas rajone
Config.TurfCapture = {
    claimThreshold = 100,
    playerCooldownSec = 90,
    turfCooldownSec = 300,
    maxProgressPerMinute = 45,
}

Config.TaskReputation = Config.TaskReputation or {}

--- Bendri paėmimo / verslo / lenktynių taškai
Config.MissionSites = {
    delivery = {
        { coords = vector4(1248.12, -3258.44, 5.80, 270.0), label = 'Konteinerių zona' },
        { coords = vector4(892.22, -3202.58, 5.90, 180.0), label = 'Uosto sandėlis' },
        { coords = vector4(2554.22, 4672.88, 34.08, 45.0), label = 'Sandy kroviniai' },
        { coords = vector4(1391.88, 3605.22, 34.98, 200.0), label = 'Sandy sandėlis' },
    },
    container = {
        { coords = vector4(1248.12, -3258.44, 5.80, 270.0), label = 'Konteinerių zona' },
        { coords = vector4(-424.88, -2789.22, 6.00, 45.0), label = 'Uosto rampa' },
        { coords = vector4(716.48, -962.12, 24.12, 0.0), label = 'La Mesa sandėlis' },
    },
    extortion = {
        { coords = vector4(24.44, -1347.22, 29.50, 270.0), label = 'Mažmeninė' },
        { coords = vector4(-706.88, -914.44, 19.22, 90.0), label = 'Parduotuvė' },
        { coords = vector4(1163.22, -323.88, 69.21, 100.0), label = 'Mirror Park' },
        { coords = vector4(-1222.44, -908.88, 12.33, 35.0), label = 'Vespucci kiosk' },
    },
    business = {
        { coords = vector4(978.44, 18.22, 81.00, 240.0), label = 'Casino biuras' },
        { coords = vector4(127.22, -1298.44, 29.23, 30.0), label = 'Downtown verslas' },
        { coords = vector4(-1569.22, -546.88, 34.96, 220.0), label = 'Richman klubas' },
        { coords = vector4(-75.44, -818.88, 326.18, 250.0), label = 'Maze Bank stogas' },
    },
    vehicle = {
        { coords = vector4(218.52, -768.24, 30.65, 160.0), label = 'Legion aikštelė', vehicle = 'sultan' },
        { coords = vector4(-340.88, -874.22, 31.08, 0.0), label = 'Downtown garažas', vehicle = 'futo' },
        { coords = vector4(1737.22, 3710.44, 34.14, 20.0), label = 'Sandy aikštelė', vehicle = 'bison' },
    },
    bike = {
        { coords = vector4(986.22, -1825.44, 31.12, 355.0), label = 'La Mesa kiemas', vehicle = 'daemon' },
        { coords = vector4(2554.22, 4672.88, 34.08, 45.0), label = 'Sandy kelias', vehicle = 'hexer' },
        { coords = vector4(-1172.44, -1572.88, 4.66, 125.0), label = 'Vespucci', vehicle = 'bagger' },
    },
    race = {
        { coords = vector4(-1037.22, -2737.88, 20.17, 330.0), label = 'Oro uosto startas', vehicle = 'sultan2' },
        { coords = vector4(1101.44, -315.22, 67.48, 0.0), label = 'Mirror Park ratas', vehicle = 'elegy2' },
        { coords = vector4(1737.22, 3710.44, 34.14, 20.0), label = 'Sandy trasa', vehicle = 'sultan2' },
    },
    mc_meet = {
        { coords = vector4(215.44, -809.88, 30.73, 250.0), label = 'MC susitikimo vieta' },
        { coords = vector4(1248.12, -3258.44, 5.80, 270.0), label = 'Uosto susitikimas' },
    },
    vip = {
        { coords = vector4(978.44, 18.22, 81.00, 240.0), label = 'VIP zona' },
        { coords = vector4(-1569.22, -546.88, 34.96, 220.0), label = 'Richman apsauga' },
    },
}

Config.MissionVisuals = {
    delivery = { prop = 'prop_cardbordbox_03a' },
    contraband = { prop = 'prop_mp_drug_package' },
    parts = { prop = 'prop_tool_box_04' },
    docs = { prop = 'prop_cs_documents_01' },
    finance = { prop = 'prop_cash_case_01' },
    extortion = { ped = 'g_m_y_lost_01', scenario = 'WORLD_HUMAN_STAND_IMPATIENT' },
    debt = { ped = 'a_m_y_stwhi_02', scenario = 'WORLD_HUMAN_SMOKING' },
    deal = { ped = 'g_m_m_mexboss_01', scenario = 'WORLD_HUMAN_STAND_IMPATIENT' },
    vip = { ped = 'a_m_m_business_01', scenario = 'WORLD_HUMAN_STAND_MOBILE' },
    drug_spot = { prop = 'prop_mp_drug_package' },
    mc_meet = { ped = 'g_m_y_lost_02', scenario = 'WORLD_HUMAN_AA_COFFEE' },
}

Config.MissionInteractDistance = 4.5
Config.MissionDropDistance = 15.0
Config.MissionMarkerDrawDistance = 90.0
Config.MissionCheckpointDistance = 12.0
Config.MissionHoldTickMs = 1000

--- Papildomi daiktai (ne OP loot)
Config.MissionBonusItems = {
    common = {
        { item = 'metalscrap', min = 1, max = 3, chance = 32 },
        { item = 'plastic', min = 1, max = 2, chance = 28 },
        { item = 'electronickit', min = 1, max = 1, chance = 18 },
    },
    uncommon = {
        { item = 'steel', min = 1, max = 2, chance = 14 },
        { item = 'rubber', min = 1, max = 2, chance = 12 },
        { item = 'gunpowder', min = 1, max = 1, chance = 8 },
    },
    rare = {
        { item = 'weapon_part', min = 1, max = 1, chance = 4 },
        { item = 'blueprint_fragment', min = 1, max = 1, chance = 2 },
        { item = 'crafting_recipe', min = 1, max = 1, chance = 1 },
    },
}

--- Atsitiktiniai scenarijai misijos metu
Config.MissionRandomEvents = {
    { id = 'npc_refuse', chance = 10, notify = 'NPC atsisako bendradarbiauti — reikia daugiau spaudimo.', extraMs = 2500 },
    { id = 'npc_flee', chance = 8, notify = 'Tikslas bando pabėgti!', extraMs = 1500 },
    { id = 'rival_gang', chance = 6, notify = 'Kita gauja atvyko į vietą — būk atsargus.' },
    { id = 'police_tip', chance = 9, notify = 'Kažkas pranešė policijai.', dispatch = true },
    { id = 'relocate', chance = 5, notify = 'Misijos vieta pasikeitė.' },
    { id = 'bonus_goal', chance = 7, notify = 'Papildomas tikslas — daugiau įtakos jei pavyks.', bonusInfluence = 2 },
}

--- Misijos: reputacija + turf įtaka + nedidelis atlygis
--- archetype: delivery | vehicle_theft | extortion | patrol | hold | graffiti | racing
Config.MissionTypes = {
    -- BIKER CLUB
    biker_lost_bike = {
        label = 'Dingęs motociklas',
        archetype = 'vehicle_theft',
        sitePool = 'bike',
        visual = 'delivery',
        reputationReward = 9,
        influenceReward = 6,
        moneyReward = 1400,
        durationMs = 6500,
        gangs = { biker = true },
        requireVehicle = true,
        dropInTurf = true,
        pickupLabel = 'Paimti motociklą',
        dropLabel = 'Pristatyti motociklą',
    },
    biker_patrol = {
        label = 'Kelio patrulis',
        archetype = 'patrol',
        reputationReward = 7,
        influenceReward = 5,
        moneyReward = 900,
        durationMs = 4000,
        gangs = { biker = true },
        checkpointCount = 4,
        dropInTurf = true,
    },
    biker_package = {
        label = 'Siuntos pristatymas',
        archetype = 'delivery',
        sitePool = 'delivery',
        visual = 'delivery',
        reputationReward = 8,
        influenceReward = 6,
        moneyReward = 1100,
        durationMs = 7000,
        gangs = { biker = true },
        spawnVehicle = 'gburrito2',
        dropInTurf = true,
    },
    biker_contraband = {
        label = 'Kontrabandos maršrutas',
        archetype = 'delivery',
        sitePool = 'container',
        visual = 'contraband',
        reputationReward = 10,
        influenceReward = 7,
        moneyReward = 1600,
        durationMs = 8000,
        gangs = { biker = true },
        spawnVehicle = 'mule3',
        dropInTurf = true,
    },
    biker_mc_meet = {
        label = 'MC susitikimas',
        archetype = 'extortion',
        sitePool = 'mc_meet',
        visual = 'mc_meet',
        reputationReward = 8,
        influenceReward = 6,
        moneyReward = 1000,
        durationMs = 7500,
        gangs = { biker = true },
        dropInTurf = false,
        pickupLabel = 'Organizuoti susitikimą',
        dropLabel = 'Užbaigti susitikimą',
    },

    -- STREET GANG
    street_graffiti = {
        label = 'Graffiti zona',
        archetype = 'graffiti',
        reputationReward = 6,
        influenceReward = 8,
        moneyReward = 750,
        durationMs = 5000,
        gangs = { street = true },
        dropInTurf = true,
    },
    street_patrol = {
        label = 'Rajono patrulis',
        archetype = 'patrol',
        reputationReward = 7,
        influenceReward = 6,
        moneyReward = 850,
        durationMs = 4000,
        gangs = { street = true },
        checkpointCount = 4,
        dropInTurf = true,
    },
    street_debts = {
        label = 'Skolų surinkimas',
        archetype = 'extortion',
        sitePool = 'extortion',
        visual = 'debt',
        reputationReward = 10,
        influenceReward = 7,
        moneyReward = 1300,
        durationMs = 7000,
        gangs = { street = true },
        dropInTurf = false,
        pickupLabel = 'Surinkti skolą',
    },
    street_drug_spot = {
        label = 'Narkotikų taškas',
        archetype = 'delivery',
        sitePool = 'delivery',
        visual = 'drug_spot',
        reputationReward = 9,
        influenceReward = 7,
        moneyReward = 1200,
        durationMs = 7500,
        gangs = { street = true },
        spawnVehicle = 'burrito3',
        dropInTurf = true,
    },
    street_hold = {
        label = 'Teritorijos kontrolė',
        archetype = 'hold',
        reputationReward = 8,
        influenceReward = 8,
        moneyReward = 950,
        durationMs = 3000,
        gangs = { street = true },
        holdSeconds = 75,
        holdRadius = 90,
        dropInTurf = true,
    },

    -- RACING CREW
    racing_test_drive = {
        label = 'Test Drive',
        archetype = 'racing',
        sitePool = 'race',
        reputationReward = 7,
        influenceReward = 5,
        moneyReward = 1100,
        durationMs = 3500,
        gangs = { racing = true },
        requireVehicle = true,
        checkpointCount = 3,
        dropInTurf = false,
    },
    racing_illegal_race = {
        label = 'Illegal Race',
        archetype = 'racing',
        sitePool = 'race',
        reputationReward = 10,
        influenceReward = 6,
        moneyReward = 1800,
        durationMs = 3000,
        gangs = { racing = true },
        requireVehicle = true,
        checkpointCount = 5,
        dropInTurf = false,
    },
    racing_vehicle_delivery = {
        label = 'Vehicle Delivery',
        archetype = 'vehicle_theft',
        sitePool = 'vehicle',
        visual = 'delivery',
        reputationReward = 9,
        influenceReward = 6,
        moneyReward = 1500,
        durationMs = 6000,
        gangs = { racing = true },
        requireVehicle = true,
        dropInTurf = true,
        pickupLabel = 'Paimti automobilį',
        dropLabel = 'Pristatyti automobilį',
    },
    racing_parts = {
        label = 'Rare Parts',
        archetype = 'delivery',
        sitePool = 'delivery',
        visual = 'parts',
        reputationReward = 8,
        influenceReward = 5,
        moneyReward = 1250,
        durationMs = 7000,
        gangs = { racing = true },
        spawnVehicle = 'speedo',
        dropInTurf = true,
        bonusItemPool = 'uncommon',
    },
    racing_chop = {
        label = 'Chop Vehicle',
        archetype = 'vehicle_theft',
        sitePool = 'vehicle',
        reputationReward = 9,
        influenceReward = 6,
        moneyReward = 1400,
        durationMs = 6500,
        gangs = { racing = true },
        requireVehicle = true,
        dropInTurf = true,
        pickupLabel = 'Paimti automobilį',
        dropLabel = 'Išardyti / pristatyti',
    },

    -- CARTEL
    cartel_container = {
        label = 'Konteinerio patikra',
        archetype = 'delivery',
        sitePool = 'container',
        visual = 'contraband',
        reputationReward = 9,
        influenceReward = 7,
        moneyReward = 1350,
        durationMs = 7500,
        gangs = { cartel = true },
        spawnVehicle = 'mule3',
        dropInTurf = true,
    },
    cartel_escort = {
        label = 'Siuntos apsauga',
        archetype = 'hold',
        sitePool = 'container',
        visual = 'contraband',
        reputationReward = 10,
        influenceReward = 7,
        moneyReward = 1450,
        durationMs = 4000,
        gangs = { cartel = true },
        holdSeconds = 60,
        holdRadius = 70,
        dropInTurf = true,
    },
    cartel_secret_deal = {
        label = 'Slaptas sandoris',
        archetype = 'extortion',
        sitePool = 'extortion',
        visual = 'deal',
        reputationReward = 11,
        influenceReward = 7,
        moneyReward = 1550,
        durationMs = 8000,
        gangs = { cartel = true },
        dropInTurf = false,
        pickupLabel = 'Atlikti sandorį',
    },
    cartel_route = {
        label = 'Maršruto kontrolė',
        archetype = 'patrol',
        reputationReward = 8,
        influenceReward = 6,
        moneyReward = 1050,
        durationMs = 4000,
        gangs = { cartel = true },
        checkpointCount = 5,
        dropInTurf = true,
    },
    cartel_supply = {
        label = 'Tiekimo grandinė',
        archetype = 'delivery',
        sitePool = 'delivery',
        visual = 'contraband',
        reputationReward = 10,
        influenceReward = 8,
        moneyReward = 1650,
        durationMs = 8000,
        gangs = { cartel = true },
        spawnVehicle = 'burrito3',
        dropInTurf = true,
        bonusItemPool = 'uncommon',
    },

    -- MAFIA
    mafia_protection = {
        label = 'Apsaugos mokestis',
        archetype = 'extortion',
        sitePool = 'business',
        visual = 'extortion',
        reputationReward = 10,
        influenceReward = 7,
        moneyReward = 1400,
        durationMs = 7000,
        gangs = { mafia = true },
        dropInTurf = false,
        pickupLabel = 'Surinkti mokestį',
    },
    mafia_business = {
        label = 'Verslo patikra',
        archetype = 'patrol',
        sitePool = 'business',
        reputationReward = 8,
        influenceReward = 6,
        moneyReward = 1100,
        durationMs = 4500,
        gangs = { mafia = true },
        checkpointCount = 3,
        dropInTurf = true,
    },
    mafia_docs = {
        label = 'Dokumentų pristatymas',
        archetype = 'delivery',
        sitePool = 'business',
        visual = 'docs',
        reputationReward = 9,
        influenceReward = 6,
        moneyReward = 1250,
        durationMs = 7000,
        gangs = { mafia = true },
        spawnVehicle = 'speedo',
        dropInTurf = true,
    },
    mafia_vip = {
        label = 'VIP apsauga',
        archetype = 'extortion',
        sitePool = 'vip',
        visual = 'vip',
        reputationReward = 11,
        influenceReward = 7,
        moneyReward = 1600,
        durationMs = 8000,
        gangs = { mafia = true },
        dropInTurf = false,
        pickupLabel = 'Saugoti VIP',
    },
    mafia_finance = {
        label = 'Finansinis sandoris',
        archetype = 'delivery',
        sitePool = 'business',
        visual = 'finance',
        reputationReward = 12,
        influenceReward = 8,
        moneyReward = 2000,
        durationMs = 9000,
        gangs = { mafia = true },
        spawnVehicle = 'speedo',
        dropInTurf = true,
    },
}

Config.HackGangRep = {
    atm = 3,
    fleeca = 8,
    store = 2,
}
