--- MDT baudų katalogas (Lietuvos KET / BK / AT koncepcijos, pritaikyta GTA RP).
--- Kiekvienas įrašas: id, category, label, code, description, amount; jailHint – tik informacinis tekstas MDT.

Config.FineCategories = {
    { id = 'ket',       label = 'KET' },
    { id = 'smulkus',   label = 'Smulkūs' },
    { id = 'vidutinis', label = 'Vidutiniai' },
    { id = 'sunkus',    label = 'Sunkūs' },
    { id = 'viesoji',   label = 'Viešoji tvarka' },
    { id = 'aplinkosauga', label = 'Aplinkosauga' },
}

--- Trumpi patarimai MDT „Bauda" skirtuke, kai pasirinkta kategorija.
Config.FineCategoryTips = {
    aplinkosauga = 'Aplinkosaugos pažeidimai: fiksuokite vietą, nuotraukas ir, jei taikoma, konfiskuokite įrankius ar medžiagas. Sunkesni atvejai — kurkite bylą ir pažymėkite kvalifikaciją „Aplinkosauga".',
}

Config.FinePresets = {
    -- ── KET (eismo taisyklės) ──────────────────────────────────────────────
    {
        id = 'ket_greitis_lengvas',
        category = 'ket',
        label = 'Greičio viršijimas (lengvas)',
        code = 'KET 127',
        description = 'Viršyta leistina greičio riba iki 20 km/h.',
        amount = 150,
    },
    {
        id = 'ket_greitis_didelis',
        category = 'ket',
        label = 'Greičio viršijimas (didelis)',
        code = 'KET 127',
        description = 'Viršyta leistina greičio riba daugiau nei 20 km/h.',
        amount = 400,
    },
    {
        id = 'ket_greitis_gyvenviete',
        category = 'ket',
        label = 'Greičio viršijimas gyvenvietėje',
        code = 'KET 127',
        description = 'Per didelis greitis gyvenamojoje zonoje arba prie mokyklos.',
        amount = 300,
    },
    {
        id = 'ket_sviesoforas',
        category = 'ket',
        label = 'Raudono šviesoforo signalo nepaisymas',
        code = 'KET 132',
        description = 'Ne sustota prie raudono šviesoforo arba nepaisytas draudžiamasis signalas.',
        amount = 220,
    },
    {
        id = 'ket_stop',
        category = 'ket',
        label = 'STOP ženklo nepaisymas',
        code = 'KET 131',
        description = 'Ne sustota prie privalomo sustojimo ženklo.',
        amount = 180,
    },
    {
        id = 'ket_kryptis',
        category = 'ket',
        label = 'Važiavimas prieš eismą',
        code = 'KET 134',
        description = 'Važiavimas neteisinga eismo kryptimi arba į važiuojamąją dalį.',
        amount = 450,
    },
    {
        id = 'ket_saugos_juosta',
        category = 'ket',
        label = 'Saugos diržo nedėvėjimas',
        code = 'KET 128',
        description = 'Vairuotojas ar keleivis be prisegto saugos diržo.',
        amount = 120,
    },
    {
        id = 'ket_salmas',
        category = 'ket',
        label = 'Šalmo nedėvėjimas (motociklas)',
        code = 'KET 129',
        description = 'Motociklo ar motorolerio vairuotojas / keleivis be šalmo.',
        amount = 100,
    },
    {
        id = 'ket_telefonas',
        category = 'ket',
        label = 'Telefono naudojimas vairuojant',
        code = 'KET 130',
        description = 'Rankomis naudojamas mobilusis telefonas ar kitas įrenginys vairuojant.',
        amount = 150,
    },
    {
        id = 'ket_parkavimas',
        category = 'ket',
        label = 'Netinkamas stovėjimas',
        code = 'KET 136',
        description = 'Transporto priemonė pastatyta ne tam skirtoje vietoje arba trukdo eismui.',
        amount = 80,
    },
    {
        id = 'ket_parkavimas_draudziama',
        category = 'ket',
        label = 'Stovėjimas draudžiamoje vietoje',
        code = 'KET 136',
        description = 'Stovėjimas prie gaisrinės, neįgaliųjų vietos, ant šaligatvio ar pėsčiųjų takų.',
        amount = 160,
    },
    {
        id = 'ket_numeriai',
        category = 'ket',
        label = 'Neįskaitomi arba neteisingi numeriai',
        code = 'KET 138',
        description = 'Valstybiniai numeriai uždengti, neįskaitomi arba neatitinka transporto priemonės.',
        amount = 350,
    },
    {
        id = 'ket_dokumentai',
        category = 'ket',
        label = 'Vairuotojo dokumentų neturėjimas',
        code = 'KET 139',
        description = 'Nepateikti vairuotojo pažymėjimo, registracijos ar draudimo dokumentų.',
        amount = 130,
    },
    {
        id = 'ket_tech',
        category = 'ket',
        label = 'Techniškai netinkama transporto priemonė',
        code = 'KET 140',
        description = 'Trūksta žibintų, stabdžių ar kitų elementų, keliančių pavojų eismui.',
        amount = 280,
    },
    {
        id = 'ket_be_teises',
        category = 'ket',
        label = 'Vairavimas be teisės',
        code = 'KET 141',
        description = 'Vairuojama neturint galiojančios vairuotojo teisės arba atimta teisė.',
        amount = 900,
        jailHint = 'Galimas sulaikymas ir transporto konfiskavimas.',
    },
    {
        id = 'ket_apsvaiges_lengvas',
        category = 'ket',
        label = 'Vairavimas apsvaigus (lengvas laipsnis)',
        code = 'KET 422',
        description = 'Vairuojama alkoholio ar narkotinių medžiagų poveikiu (lengvas atvejis).',
        amount = 1800,
        jailHint = 'Privalomas blaivumo tikrinimas; galimas sulaikymas.',
    },
    {
        id = 'ket_apsvaiges_sunkus',
        category = 'ket',
        label = 'Vairavimas apsvaigus (sunkus laipsnis)',
        code = 'KET 422',
        description = 'Ryškus apsvaigimas vairuojant; kelia didelį pavojų kitiems eismo dalyviams.',
        amount = 4000,
        jailHint = 'Sulaikymas, teisės atėmimas, transporto konfiskavimas.',
    },
    {
        id = 'ket_pavojingas',
        category = 'ket',
        label = 'Pavojingas ar neatsargus vairavimas',
        code = 'KET 133',
        description = 'Driftas, persokinėjimas per eismą, agresyvus manevravimas ar pavojingas lenkimasis.',
        amount = 550,
    },
    {
        id = 'ket_lenkimas',
        category = 'ket',
        label = 'Lenkimasis per ištisinę liniją',
        code = 'KET 135',
        description = 'Lenkimasis ten, kur eismo taisyklės draudžia (ištisinė linija, kirtimas per dvipusį eismą).',
        amount = 380,
    },
    {
        id = 'ket_pesciu_perkela',
        category = 'ket',
        label = 'Pėsčiųjų perėjos pažeidimas',
        code = 'KET 137',
        description = 'Ne suteikta pirmenybė pėstiesiems perėjoje arba važiavimas per raudoną pėsčių signalą.',
        amount = 240,
    },
    {
        id = 'ket_eismo_ivykis',
        category = 'ket',
        label = 'Pabėgimas nuo eismo įvykio vietos',
        code = 'KET 424',
        description = 'Palikta eismo įvykio vieta nepranešus ir nepalikus reikiamos informacijos.',
        amount = 1500,
        jailHint = 'Galimas ikiteisminis tyrimas.',
    },
    {
        id = 'ket_evakuatorius',
        category = 'ket',
        label = 'Transporto priemonės nutempimas (administracinis)',
        code = 'KET 143',
        description = 'Transporto priemonė nutempta dėl netinkamo stovėjimo arba eismo taisyklių pažeidimo.',
        amount = 450,
    },
    {
        id = 'ket_tamsinimas',
        category = 'ket',
        label = 'Nelegalus stiklų tamsinimas',
        code = 'KET 138',
        description = 'Langai patamsinti daugiau nei leidžia techniniai reikalavimai; trukdo matomumui.',
        amount = 200,
    },
    {
        id = 'ket_kroviniu',
        category = 'ket',
        label = 'Nesaugus krovinių tvirtinimas',
        code = 'KET 140',
        description = 'Krovinys netinkamai sutvirtintas, viršija leistinas ribas arba kelia pavojų kitiems.',
        amount = 320,
    },
    {
        id = 'ket_sankryza',
        category = 'ket',
        label = 'Sankryžos blokavimas',
        code = 'KET 133',
        description = 'Transporto priemonė sustojo ant sankryžos ir trukdo eismui, kai šviesoforas jau raudonas.',
        amount = 260,
    },
    {
        id = 'ket_greitoji',
        category = 'ket',
        label = 'Specialiosios pagalbos juostos / avarinės stovėjimo vietos užėmimas',
        code = 'KET 136',
        description = 'Stovėjimas ar važiavimas gaisrinės / greitosios pagalbos juostoje ar prie jų stovėjimo vietų.',
        amount = 420,
    },
    {
        id = 'ket_mokykla',
        category = 'ket',
        label = 'Mokyklos zonos pažeidimas',
        code = 'KET 127',
        description = 'Per didelis greitis, netinkamas stovėjimas ar pavojingas manevras prie mokyklos ar vaikų zonos.',
        amount = 350,
    },
    {
        id = 'ket_draudimas',
        category = 'ket',
        label = 'Vairavimas be civilinės atsakomybės draudimo',
        code = 'KET 139',
        description = 'Transporto priemonė naudojama be galiojančio draudimo poliso (RP).',
        amount = 480,
    },
    {
        id = 'ket_registracija',
        category = 'ket',
        label = 'Neregistruota transporto priemonė',
        code = 'KET 139',
        description = 'Važiuojama neįregistruota arba nelegaliai modifikuota transporto priemonė.',
        amount = 520,
    },
    {
        id = 'ket_garsas',
        category = 'ket',
        label = 'Per garsi išmetimo sistema / triukšmas',
        code = 'KET 140',
        description = 'Išmetimo sistema modifikuota taip, kad viršijamas leistinas triukšmo lygis.',
        amount = 280,
    },
    {
        id = 'ket_zibintai',
        category = 'ket',
        label = 'Neįjungti žibintai tamsiu paros metu',
        code = 'KET 140',
        description = 'Važiuojama be artimųjų ar tolimųjų šviesų, kai tai privaloma.',
        amount = 140,
    },
    {
        id = 'ket_atstumas',
        category = 'ket',
        label = 'Nepakankamas atstumas iki priekyje važiuojančios transporto priemonės',
        code = 'KET 133',
        description = 'Važiuojama per arti kitos transporto priemonės (tailgating).',
        amount = 190,
    },
    {
        id = 'ket_pirmenybe',
        category = 'ket',
        label = 'Pirmenybės nesuteikimas',
        code = 'KET 137',
        description = 'Ne suteikta pirmenybė sankryžoje, posūkyje ar įvažiavime pagal kelio ženklus.',
        amount = 210,
    },
    {
        id = 'ket_autobusas',
        category = 'ket',
        label = 'Autobusų juostos pažeidimas',
        code = 'KET 134',
        description = 'Važiavimas ar stovėjimas autobusų ar viešojo transporto juostoje ne tam skirtoje vietoje.',
        amount = 240,
    },
    {
        id = 'ket_pesciu_zona',
        category = 'ket',
        label = 'Važiavimas pėsčiųjų zona',
        code = 'KET 134',
        description = 'Transporto priemonė važiavo pėsčiųjų takais, aikštėmis ar draudžiamoje zonoje.',
        amount = 380,
    },
    {
        id = 'ket_vaikai',
        category = 'ket',
        label = 'Vaikas be vaikų kėdutės',
        code = 'KET 128',
        description = 'Vaikas vežamas be atitinkamo amžiui pritaikyto saugos įtaiso.',
        amount = 170,
    },
    {
        id = 'ket_blaivumo_atsisakymas',
        category = 'ket',
        label = 'Atsisakymas blaivumo patikrinimo',
        code = 'KET 422',
        description = 'Vairuotojas atsisakė blaivumo tikrinimo arba nepakluso teisėtam patikrinimui.',
        amount = 2500,
        jailHint = 'Galimas sulaikymas ir teisės atėmimas.',
    },
    {
        id = 'ket_kelio_darbai',
        category = 'ket',
        label = 'Kelio darbų zonos pažeidimas',
        code = 'KET 133',
        description = 'Neįvertintos kelio ženklai, barjerai ar darbų zonos ribojimai.',
        amount = 300,
    },
    {
        id = 'ket_neisjungtas_variklis',
        category = 'ket',
        label = 'Palikta transporto priemonė su veikiančiu varikliu',
        code = 'KET 136',
        description = 'Transporto priemonė palikta su įjungtu varikliu ne tam skirtoje vietoje.',
        amount = 90,
    },
    {
        id = 'ket_perdengimas_sankryzoje',
        category = 'ket',
        label = 'Lenkimasis sankryžoje',
        code = 'KET 135',
        description = 'Lenkimasis ar persokinėjimas per eismą sankryžoje, kur tai draudžiama.',
        amount = 420,
    },
    {
        id = 'ket_neislaikytas_kelias',
        category = 'ket',
        label = 'Važiavimas ne savo eismo juosta',
        code = 'KET 134',
        description = 'Ilgesnis laikas važiuojama ne savo juosta arba kertamos ištisinės linijos be reikalo.',
        amount = 230,
    },
    {
        id = 'ket_sukimas_uz_draudimo',
        category = 'ket',
        label = 'Posūkis / apsisukimas draudžiamoje vietoje',
        code = 'KET 134',
        description = 'Atliktas posūkis ar apsisukimas ten, kur kelio ženklai ar linijos tai draudžia.',
        amount = 200,
    },
    {
        id = 'ket_eismo_ivykis_lengvas',
        category = 'ket',
        label = 'Eismo įvykis be sustojimo (lengvas)',
        code = 'KET 424',
        description = 'Palikta eismo įvykio vieta po lengvo kontakto ar apgadinimo be duomenų palikimo.',
        amount = 800,
        jailHint = 'Galimas papildomas tyrimas.',
    },
    {
        id = 'ket_neislaikytas_atstumas_motociklas',
        category = 'ket',
        label = 'Pavojingas važiavimas tarp eismo juostų (motociklas)',
        code = 'KET 133',
        description = 'Motociklas persokinėja per eismą ar važiuoja tarp eismo juostų pavojingai arti kitų transporto priemonių.',
        amount = 340,
    },

    -- ── Smulkūs pažeidimai ───────────────────────────────────────────────────
    {
        id = 'sm_triuksmas',
        category = 'smulkus',
        label = 'Triukšmo / ramybės pažeidimas',
        code = 'BK 284',
        description = 'Garsus triukšmas naktį, garsinė sistema arba triukšmingas elgesys viešoje vietoje.',
        amount = 150,
    },
    {
        id = 'sm_siukšles',
        category = 'smulkus',
        label = 'Šiukšlių metimas viešoje vietoje',
        code = 'BK 284',
        description = 'Šiukšlių palikimas gatvėje, parke ar kitoje viešoje erdvėje.',
        amount = 100,
    },
    {
        id = 'sm_trespass',
        category = 'smulkus',
        label = 'Neteisėtas patekimas į privačią teritoriją',
        code = 'BK 285',
        description = 'Patekimas į uždarytą objektą ar privatią teritoriją be leidimo.',
        amount = 200,
    },
    {
        id = 'sm_girtumas',
        category = 'smulkus',
        label = 'Girtumas viešoje vietoje',
        code = 'BK 486',
        description = 'Asmuo viešoje vietoje apsvaigęs ir trukdo viešajai tvarkai.',
        amount = 250,
    },
    {
        id = 'sm_nepaklusnumas',
        category = 'smulkus',
        label = 'Nepaklusnumas pareigūnui (lengvas)',
        code = 'BK 287',
        description = 'Nesilaikoma teisėtų pareigūno nurodymų, neagresyvus elgesys.',
        amount = 350,
    },
    {
        id = 'sm_veidas',
        category = 'smulkus',
        label = 'Veido maskavimas viešoje vietoje',
        code = 'BK 286',
        description = 'Veidas uždengtas kaukė, kapišonu ar kita priemone be pagrįstos priežasties.',
        amount = 180,
    },
    {
        id = 'sm_susirinkimas',
        category = 'smulkus',
        label = 'Neteisėtas susirinkimas',
        code = 'BK 288',
        description = 'Nesankcionuotas susirinkimas, trukdantis eismui ar viešajai tvarkai.',
        amount = 400,
    },
    {
        id = 'sm_vagis_maza',
        category = 'smulkus',
        label = 'Vagystė (smulkus daiktas)',
        code = 'BK 178',
        description = 'Paimtas mažos vertės daiktas be smurto (pvz., parduotuvėje).',
        amount = 600,
    },
    {
        id = 'sm_budejimas',
        category = 'smulkus',
        label = 'Be tikslo slampinėjimas / budėjimas',
        code = 'ATPK 41',
        description = 'Asmuo ilgai stovėjo ar slampinėjo vietoje be aiškaus tikslo ir trukdė eismui ar ramybei.',
        amount = 120,
    },
    {
        id = 'sm_slapinimasis',
        category = 'smulkus',
        label = 'Šlapinimasis viešoje vietoje',
        code = 'ATPK 41',
        description = 'Fiziologiniai poreikiai tenkinami viešoje erdvėje, trukdant kitiems.',
        amount = 180,
    },
    {
        id = 'sm_feuerwerkas',
        category = 'smulkus',
        label = 'Pirotechnikos naudojimas draudžiamoje vietoje',
        code = 'BK 284',
        description = 'Fejerverkai, petardos ar kiti pirotechniniai gaminiai naudojami mieste be leidimo.',
        amount = 350,
    },
    {
        id = 'sm_gyvunas',
        category = 'smulkus',
        label = 'Gyvūnas be pavadėlio / antsnukio',
        code = 'ATPK 41',
        description = 'Augintinis vedžiojamas viešoje vietoje be pavadėlio arba agresyvus gyvūnas be antsnukio.',
        amount = 140,
    },
    {
        id = 'sm_tapatybe_lengva',
        category = 'smulkus',
        label = 'Tapatybės nurodymo vengimas (lengvas)',
        code = 'BK 287',
        description = 'Asmuo vengia nurodyti tikrą vardą ar pateikia klaidingą informaciją be dokumentų klastojimo.',
        amount = 280,
    },
    {
        id = 'sm_lenta',
        category = 'smulkus',
        label = 'Riedėjimas riedučiais / lentomis pėsčiųjų zonoje',
        code = 'ATPK 41',
        description = 'Riedučiais, riedlente ar paspirtuku važinėjama pėsčiųjų takais pavojingai arti žmonių.',
        amount = 110,
    },
    {
        id = 'sm_rukymas',
        category = 'smulkus',
        label = 'Rūkymas draudžiamoje vietoje',
        code = 'ATPK 41',
        description = 'Rūkoma viešojo transporto stotelėse, ligoninėse ar kitaose draudžiamose zonose.',
        amount = 80,
    },
    {
        id = 'sm_elgeta',
        category = 'smulkus',
        label = 'Elgetavimas / neleistina paramos prašymas',
        code = 'ATPK 41',
        description = 'Agresyviai ar neleistinoje vietoje prašoma pinigų ar paramos.',
        amount = 130,
    },
    {
        id = 'sm_reklama',
        category = 'smulkus',
        label = 'Nelegali reklama / skrajutės',
        code = 'ATPK 41',
        description = 'Klijuojamos skrajutės, plakatai ar reklama ant viešos nuosavybės be leidimo.',
        amount = 160,
    },
    {
        id = 'sm_filmas',
        category = 'smulkus',
        label = 'Filmavimas trukdant pareigūnams',
        code = 'BK 287',
        description = 'Filmuojama ar fotografuojama iš arti, trukdant teisėtai pareigūnų veiklai.',
        amount = 220,
    },
    {
        id = 'sm_neislaikytas_komendanto',
        category = 'smulkus',
        label = 'Komendanto valandos pažeidimas (lengvas)',
        code = 'ATPK 41',
        description = 'Asmuo viešoje vietoje neleistinu laiku be pagrįstos priežasties (jei galioja RP taisyklės).',
        amount = 300,
    },
    {
        id = 'nark_vartojimas',
        category = 'smulkus',
        label = 'Narkotikų vartojimas viešoje vietoje',
        code = 'BK 259',
        description = 'Vartojamos narkotinės medžiagos viešoje erdvėje.',
        amount = 900,
    },

    -- ── Vidutinio sunkumo ────────────────────────────────────────────────────
    {
        id = 'vid_vagyste',
        category = 'vidutinis',
        label = 'Vagystė',
        code = 'BK 178',
        description = 'Pagrobta svetima nuosavybė be smurto ar su lengvu smurtu.',
        amount = 1500,
        jailHint = 'Galimas sulaikymas ir ikiteisminis tyrimas.',
    },
    {
        id = 'vid_plesimas',
        category = 'vidutinis',
        label = 'Plėšimas (grasinant)',
        code = 'BK 178',
        description = 'Nuosavybė atimta grasinant ar naudojant psichologinį spaudimą.',
        amount = 2200,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'vid_smurtas',
        category = 'vidutinis',
        label = 'Fizinis smurtas / muštynės',
        code = 'BK 140',
        description = 'Fizinis smurtas ar muštynės viešoje vietoje be ginklo.',
        amount = 1800,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'vid_grasinimas',
        category = 'vidutinis',
        label = 'Grasinimas / bauginimas',
        code = 'BK 145',
        description = 'Grasinama kūnu sužaloti, nužudyti ar padaryti materialinę žalą.',
        amount = 900,
    },
    {
        id = 'vid_ginklas_rodomas',
        category = 'vidutinis',
        label = 'Ginklo demonstravimas viešoje vietoje',
        code = 'BK 260',
        description = 'Ginklas ištrauktas ir demonstruojamas be teisėto pagrindo.',
        amount = 2000,
        jailHint = 'Galimas ginklo konfiskavimas.',
    },
    {
        id = 'vid_isilauzimas',
        category = 'vidutinis',
        label = 'Įsilaužimas',
        code = 'BK 179',
        description = 'Neteisėtas patekimas į pastatą, transporto priemonę ar saugomą patalpą.',
        amount = 2000,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'vid_rezistavimas',
        category = 'vidutinis',
        label = 'Pasipriešinimas sulaikymui',
        code = 'BK 287',
        description = 'Aktyvus pasipriešinimas teisėtam sulaikymui ar kratimui.',
        amount = 1600,
        jailHint = 'Papildomas sulaikymas.',
    },
    {
        id = 'vid_dokumentu_klastojimas',
        category = 'vidutinis',
        label = 'Dokumentų klastojimas',
        code = 'BK 300',
        description = 'Naudojami suklastoti ar svetimi tapatybės / vairuotojo dokumentai.',
        amount = 1200,
    },
    {
        id = 'vid_nark_lengva',
        category = 'vidutinis',
        label = 'Narkotinių medžiagų turėjimas (lengvas kiekis)',
        code = 'BK 259',
        description = 'Turimos nedidelės narkotinių medžiagų dozės asmeniniam vartojimui.',
        amount = 1500,
        jailHint = 'Medžiagos konfiskavimas; galimas sulaikymas.',
    },
    {
        id = 'vid_vandalizmas',
        category = 'vidutinis',
        label = 'Turto ar transporto priemonės vandalizmas',
        code = 'BK 289',
        description = 'Tyčia apgadinta svetima nuosavybė, automobilis, fasadas ar langai.',
        amount = 1100,
    },
    {
        id = 'vid_vogti_numeriai',
        category = 'vidutinis',
        label = 'Vogti ar suklastoti valstybiniai numeriai',
        code = 'BK 300',
        description = 'Ant transporto priemonės montuoti svetimi, vogti ar suklastoti numeriai.',
        amount = 1400,
        jailHint = 'Transporto priemonės sulaikymas.',
    },
    {
        id = 'vid_sekimas',
        category = 'vidutinis',
        label = 'Persekiojimas / sekimas (stalking RP)',
        code = 'BK 145',
        description = 'Asmuo sistemingai sekamas, stebimas ar bauginamas be teisėto pagrindo.',
        amount = 1300,
    },
    {
        id = 'vid_losimas',
        category = 'vidutinis',
        label = 'Nelegalus lošimas / azartinių lošimų organizavimas',
        code = 'BK 292',
        description = 'Organizuojami nelegalūs lošimai, kortų stalai ar statymai be licencijos.',
        amount = 1700,
    },
    {
        id = 'vid_transporto_vagyste',
        category = 'vidutinis',
        label = 'Transporto priemonės vagystė',
        code = 'BK 178',
        description = 'Pagrobta svetima transporto priemonė ar bandymas ją pagrobti.',
        amount = 2500,
        jailHint = 'Galimas sulaikymas; transporto konfiskavimas.',
    },
    {
        id = 'vid_isprievartavimas_grasinimas',
        category = 'vidutinis',
        label = 'Seksualinis priekabiavimas / grasinimas',
        code = 'BK 150',
        description = 'Nepageidaujamas fizinis kontaktas, priekabiavimas ar seksualinio pobūdžio grasinimai.',
        amount = 1900,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'vid_isrinkimo',
        category = 'vidutinis',
        label = 'Reketas / extortion (lengvas laipsnis)',
        code = 'BK 145',
        description = 'Reikalaujama pinigų ar naudos grasinant smurtu ar žalos padarymu.',
        amount = 2100,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'vid_klastotas_draudimas',
        category = 'vidutinis',
        label = 'Suklastotas draudimo ar registracijos dokumentas',
        code = 'BK 300',
        description = 'Pateiktas ar naudojamas suklastotas draudimo polisas ar registracijos liudijimas.',
        amount = 1150,
    },
    {
        id = 'vid_nelegali_taksi',
        category = 'vidutinis',
        label = 'Nelegali keleivių pervežimo paslauga',
        code = 'ATPK 41',
        description = 'Vežami keleiviai už mokestį be licencijos ar leidimo (RP taksi / Uber).',
        amount = 950,
    },
    {
        id = 'vid_ginkluotas_grasinimas',
        category = 'vidutinis',
        label = 'Ginkluotas grasinimas (be šūvio)',
        code = 'BK 260',
        description = 'Ginklas nukreiptas ar parodytas grasinant, bet nešauta.',
        amount = 2400,
        jailHint = 'Ginklo konfiskavimas; galimas sulaikymas.',
    },
    {
        id = 'vid_netikslus_pranesimas',
        category = 'vidutinis',
        label = 'Melagingas pranešimas apie nusikaltimą',
        code = 'BK 235',
        description = 'Tyčia pateikta klaidinga informacija policijai ar greitajai pagalbai.',
        amount = 1400,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'vid_nelegalus_prekyba',
        category = 'vidutinis',
        label = 'Nelegali prekyba / prekyba be licencijos',
        code = 'ATPK 41',
        description = 'Prekiaujama alkoholiu, tabaku ar kitais apribotais produktais be leidimo.',
        amount = 1250,
    },
    {
        id = 'vid_kibernetinis',
        category = 'vidutinis',
        label = 'Neteisėta prieiga prie sistemų (RP)',
        code = 'BK 215',
        description = 'Bandymas įsilaužti į bankomatą, MDT, telefoną ar kitą apsaugotą sistemą.',
        amount = 1650,
    },
    {
        id = 'gink_be_licencijos',
        category = 'vidutinis',
        label = 'Ginklo nešiojimas be licencijos',
        code = 'BK 260',
        description = 'Ginklas nešiojamas neturint galiojančios ginklo licencijos.',
        amount = 2200,
        jailHint = 'Ginklo konfiskavimas.',
    },
    {
        id = 'gink_viesoje',
        category = 'vidutinis',
        label = 'Ginklo nešiojimas viešoje vietoje',
        code = 'BK 260',
        description = 'Ginklas matomas ar nešiojamas viešoje erdvėje be teisėto pagrindo.',
        amount = 2800,
        jailHint = 'Ginklo konfiskavimas; galimas sulaikymas.',
    },
    {
        id = 'gink_perdavimas',
        category = 'vidutinis',
        label = 'Ginklo perdavimas neįgaliotam asmeniui',
        code = 'BK 260',
        description = 'Ginklas perduotas asmeniui be licencijos ar nepilnamečiui.',
        amount = 3500,
        jailHint = 'Galimas sulaikymas.',
    },
    {
        id = 'nark_turejimas',
        category = 'vidutinis',
        label = 'Narkotinių medžiagų turėjimas',
        code = 'BK 259',
        description = 'Turimos narkotinės medžiagos asmeniniam vartojimui.',
        amount = 1300,
        jailHint = 'Konfiskavimas; galimas sulaikymas.',
    },

    -- ── Sunkūs pažeidimai ────────────────────────────────────────────────────
    {
        id = 'sunk_ginkluotas_plesimas',
        category = 'sunkus',
        label = 'Ginkluotas plėšimas',
        code = 'BK 178',
        description = 'Plėšimas naudojant ginklą arba ginklo imitaciją.',
        amount = 9000,
        jailHint = 'Privalomas sulaikymas; ikiteisminis tyrimas.',
    },
    {
        id = 'sunk_sunkus_suzalojimas',
        category = 'sunkus',
        label = 'Sunkus kūno sužalojimas',
        code = 'BK 140',
        description = 'Tyčia padarytas sunkus kūno sužalojimas arba gyvybei pavojinga situacija.',
        amount = 7000,
        jailHint = 'Privalomas sulaikymas.',
    },
    {
        id = 'sunk_pabegimas_policija',
        category = 'sunkus',
        label = 'Pabėgimas nuo policijos',
        code = 'BK 287',
        description = 'Aktyvus bėgimas ar transporto priemonės vartojimas bėgant nuo pareigūnų.',
        amount = 5500,
        jailHint = 'Privalomas sulaikymas; transporto konfiskavimas.',
    },
    {
        id = 'sunk_grobis',
        category = 'sunkus',
        label = 'Žmogaus grobis / neteisėtas laisvės atėmimas',
        code = 'BK 157',
        description = 'Asmuo pagrobta arba neteisėtai sulaikyta prieš jo valią.',
        amount = 10000,
        jailHint = 'Privalomas sulaikymas; ikiteisminis tyrimas.',
    },
    {
        id = 'sunk_pasikėsinimas',
        category = 'sunkus',
        label = 'Pasikėsinimas į gyvybę',
        code = 'BK 129',
        description = 'Tyčinis pasikėsinimas nužudyti arba šaudymas į asmenį.',
        amount = 12000,
        jailHint = 'Privalomas ilgas sulaikymas.',
    },
    {
        id = 'sunk_teroristinis',
        category = 'sunkus',
        label = 'Teroristinis grasinimas (RP)',
        code = 'BK 133',
        description = 'Masinis grasinimas, sprogmenų imitacija ar koordinuotas smurto aktas.',
        amount = 15000,
        jailHint = 'Federalinis / ilgas sulaikymas.',
    },
    {
        id = 'sunk_banko_plesimas',
        category = 'sunkus',
        label = 'Organizuotas plėšimas (bankas / kasos)',
        code = 'BK 178',
        description = 'Plėšimas finansų įstaigoje ar kasoje su ginklu arba organizuota grupe.',
        amount = 11000,
        jailHint = 'Privalomas sulaikymas; ikiteisminis tyrimas.',
    },
    {
        id = 'gink_nelegalus',
        category = 'sunkus',
        label = 'Nelegalus ginklas / automatinis ginklas',
        code = 'BK 260',
        description = 'Turimas automatinis ginklas, nelegali modifikacija ar draudžiamas ginklo tipas.',
        amount = 5000,
        jailHint = 'Privalomas konfiskavimas ir sulaikymas.',
    },
    {
        id = 'gink_saudymas',
        category = 'sunkus',
        label = 'Šaudymas gyvenamojoje zonoje',
        code = 'BK 260',
        description = 'Šaudyta ar ginklas panaudotas mieste be teisėtos gynybos.',
        amount = 4000,
        jailHint = 'Privalomas sulaikymas.',
    },
    {
        id = 'nark_platinimas',
        category = 'sunkus',
        label = 'Narkotikų platinimas',
        code = 'BK 259',
        description = 'Parduodamos ar perduodamos narkotinės medžiagos tretiesiems asmenims.',
        amount = 8500,
        jailHint = 'Privalomas sulaikymas; ikiteisminis tyrimas.',
    },
    {
        id = 'nark_gamyba',
        category = 'sunkus',
        label = 'Narkotikų gaminimas / auginimas',
        code = 'BK 259',
        description = 'Gaminamos, perdirbamos ar auginamos narkotinės medžiagos.',
        amount = 10000,
        jailHint = 'Privalomas sulaikymas; konfiskavimas.',
    },
    {
        id = 'nark_didele_kiekis',
        category = 'sunkus',
        label = 'Didelis narkotikų kiekis (platintojo profilis)',
        code = 'BK 259',
        description = 'Turimas didelis kiekis, rodomas prekybos ar platinimo požymis.',
        amount = 6500,
        jailHint = 'Privalomas sulaikymas.',
    },

    -- ── Viešoji tvarka ───────────────────────────────────────────────────────
    {
        id = 'vt_riaušes',
        category = 'viesoji',
        label = 'Riaušės / masinis triukšmas',
        code = 'BK 288',
        description = 'Grupinis elgesys, trukdantis viešajai tvarkai ar keliantis pavojų aplinkiniams.',
        amount = 650,
    },
    {
        id = 'vt_gadynimas',
        category = 'viesoji',
        label = 'Viešosios nuosavybės gadynimas',
        code = 'BK 289',
        description = 'Sugadinta municipalinė nuosavybė, stendas, apšvietimas ar kitas viešas objektas.',
        amount = 550,
    },
    {
        id = 'vt_impersonation',
        category = 'viesoji',
        label = 'Apsimetinėjimas valstybės pareigūnu',
        code = 'BK 301',
        description = 'Apsimesta policininku, mediku ar kitu pareigūnu siekiant naudos.',
        amount = 4500,
        jailHint = 'Privalomas sulaikymas.',
    },
    {
        id = 'vt_korupcija',
        category = 'viesoji',
        label = 'Kyšininkavimas pareigūnui',
        code = 'BK 302',
        description = 'Siūlomi pinigai ar nauda siekiant išvengti atsakomybės.',
        amount = 3000,
        jailHint = 'Galimas sulaikymas.',
    },

    -- ── Aplinkosauga ─────────────────────────────────────────────────────────
    {
        id = 'ap_siukšles_gamta',
        category = 'aplinkosauga',
        label = 'Šiukšlių metimas gamtoje / miške',
        code = 'AĮ 70',
        description = 'Atliekos, statybinės šiukšlės ar buitinėms atliekoms prilygstantys daiktai palikti miške, krante ar kitoje ne tam skirtoje vietoje.',
        amount = 180,
    },
    {
        id = 'ap_netekstas_salinimas',
        category = 'aplinkosauga',
        label = 'Neteisėtas atliekų išmetimas / savavališkas sąvartynas',
        code = 'AĮ 70',
        description = 'Atliekos paliktos nelegalioje vietoje, griovyje, pakrantėje ar neleistinoje aikštelėje.',
        amount = 450,
    },
    {
        id = 'ap_vandens_tarsa',
        category = 'aplinkosauga',
        label = 'Vandens telkinio taršimas',
        code = 'AĮ 92',
        description = 'Į upę, ežerą, kanalizaciją ar jūrą išmesta cheminė medžiaga, dažai, statybinės atliekos ar kitas teršalas.',
        amount = 1200,
        jailHint = 'Galimas ikiteisminis tyrimas; praneškite aplinkosaugos tarnyboms (RP).',
    },
    {
        id = 'ap_naftos_issiliejimas',
        category = 'aplinkosauga',
        label = 'Naftos produktų išsiliejimas (transporto priemonė)',
        code = 'AĮ 92',
        description = 'Ant žemės ar vandens pateko degalai, alyva ar kiti naftos produktai dėl TP gedimo, avarijos ar tyčinio veiksmo.',
        amount = 800,
    },
    {
        id = 'ap_neteiseta_zvejyba',
        category = 'aplinkosauga',
        label = 'Žvejyba be leidimo / draudžiamoje zonoje',
        code = 'ŽĮ 45',
        description = 'Žvejojama be galiojančios licencijos, ne leistinu metu, draudžiamu įrankiu ar saugomoje teritorijoje.',
        amount = 350,
    },
    {
        id = 'ap_neteiseta_medziokle',
        category = 'aplinkosauga',
        label = 'Medžioklė be licencijos / ne sezonu',
        code = 'MĮ 38',
        description = 'Medžiojama be leidimo, ne sezonu, saugomoje vietovėje ar naudojant draudžiamus įrankius.',
        amount = 600,
        jailHint = 'Konfiskuokite ginklą ir grobį; galimas ikiteisminis tyrimas.',
    },
    {
        id = 'ap_saugoma_teritorija',
        category = 'aplinkosauga',
        label = 'Patekimas į saugomą gamtos teritoriją',
        code = 'AĮ 47',
        description = 'Asmuo ar transporto priemonė pateko į draudžiamą rezervatą, gamtos parką ar kitą saugomą zoną.',
        amount = 400,
    },
    {
        id = 'ap_offroad_zala',
        category = 'aplinkosauga',
        label = 'Važiavimas be kelio / off-road žala gamtoje',
        code = 'AĮ 47',
        description = 'Transporto priemonė važiavo ne keliu, pažeisdama dirvožemį, augmeniją ar gamtos takus.',
        amount = 550,
    },
    {
        id = 'ap_nelegalus_kirtimas',
        category = 'aplinkosauga',
        label = 'Nelegalus medžių kirtimas',
        code = 'MĮ 61',
        description = 'Kertami ar kirti medžiai be leidimo, saugomoje vietovėje ar didesniu nei leistina kiekiu.',
        amount = 1500,
        jailHint = 'Konfiskuokite įrankius; galimas ikiteisminis tyrimas.',
    },
    {
        id = 'ap_atlieku_deginimas',
        category = 'aplinkosauga',
        label = 'Atliekų deginimas atvirame ore',
        code = 'AĮ 30',
        description = 'Plastikas, padangos, statybinės ar buitinės atliekos deginamos kieme, miške ar kitoje ne tam skirtoje vietoje.',
        amount = 380,
    },
    {
        id = 'ap_gyvunu_kankinimas_lengvas',
        category = 'aplinkosauga',
        label = 'Gyvūno nepriežiūra / kankinimas (lengvas)',
        code = 'GGĮ 7',
        description = 'Gyvūnas laikomas be maisto, vandens, pastogės ar kitaip kenksmingomis sąlygomis.',
        amount = 250,
    },
    {
        id = 'ap_gyvunu_kankinimas_vidutinis',
        category = 'aplinkosauga',
        label = 'Gyvūno kankinimas (vidutinis)',
        code = 'GGĮ 7',
        description = 'Tyčinis smurtas prieš gyvūną, agresyvus elgesys ar ilgalaikė nepriežiūra su aiškiais sužalojimais.',
        amount = 900,
        jailHint = 'Galimas gyvūno paėmimas ir ikiteisminis tyrimas.',
    },
    {
        id = 'ap_dumu_tarsa',
        category = 'aplinkosauga',
        label = 'Per didelis dūmų / taršos išmetimas (TP)',
        code = 'AĮ 25',
        description = 'Transporto priemonė išmeta per daug dūmų, suodžių ar kenksmingų dujų, viršijant leistinas normas.',
        amount = 320,
    },
    {
        id = 'ap_pavojingos_atliekos',
        category = 'aplinkosauga',
        label = 'Pavojingų atliekų transportavimas be leidimo',
        code = 'AĮ 30',
        description = 'Cheminės, medicininės ar kitos pavojingos atliekos vežamos be dokumentų, ženklinimo ar saugaus tvirtinimo.',
        amount = 2200,
        jailHint = 'Sulaikykite TP; praneškite specializuotoms tarnyboms (RP).',
    },
    {
        id = 'ap_papludimio_zala',
        category = 'aplinkosauga',
        label = 'Paplūdimio / parko erdvės gadynimas',
        code = 'AĮ 47',
        description = 'Sugadinta pakrantė, pieva, takai, suoliukai ar kitas viešas gamtos / poilsio objektas.',
        amount = 280,
    },
    {
        id = 'ap_gamtos_paminklas',
        category = 'aplinkosauga',
        label = 'Žala saugomam gamtos objektui / paminklui',
        code = 'AĮ 47',
        description = 'Apgadintas ar užterštas saugomas medis, uola, gamtos formacija ar kultūros paveldo objektas gamtoje.',
        amount = 1800,
        jailHint = 'Kurkite bylą; galimas perdavimas prokuratūrai.',
    },
    {
        id = 'ap_statybines_atliekos',
        category = 'aplinkosauga',
        label = 'Statybinių atliekų palikimas ne tam skirtoje vietoje',
        code = 'AĮ 30',
        description = 'Statybinės atliekos, griuvėsiai ar statybinė medžiaga palikta gatvėje, miške ar nelegalioje vietoje.',
        amount = 650,
    },
    {
        id = 'ap_garsas_gamta',
        category = 'aplinkosauga',
        label = 'Triukšmas saugomoje gamtos zonoje',
        code = 'AĮ 41',
        description = 'Per garsi muzika, generatorius, fejerverkai ar kitas triukšmas gamtos rezervate ar ramybės zonoje.',
        amount = 200,
    },
    {
        id = 'ap_rusiuojimo_pažeidimas',
        category = 'aplinkosauga',
        label = 'Atliekų rūšiavimo taisyklių pažeidimas (didelis kiekis)',
        code = 'AĮ 30',
        description = 'Mišrios atliekos paliktos vietoje, kur privalomas rūšiavimas, arba sąmoningai maišomos pavojingos medžiagos.',
        amount = 170,
    },
    {
        id = 'ap_zalioji_zona',
        category = 'aplinkosauga',
        label = 'Veikla draudžiamoje žaliojoje zonoje',
        code = 'AĮ 47',
        description = 'Statyba, kasimas, stovėjimas ar komercinė veikla draudžiamoje žaliojoje juostoje ar saugomame sklype.',
        amount = 2500,
        jailHint = 'Sustabdykite veiklą; kurkite bylą ir informuokite savivaldybę (RP).',
    },
}
