--- Visos pasaulio šalys (LT pavadinimai)
Countries = {
    'Afganistanas', 'Albanija', 'Alžyras', 'Andora', 'Angola', 'Antigva ir Barbuda', 'Argentina', 'Armėnija',
    'Australija', 'Austrija', 'Azerbaidžanas', 'Bahamos', 'Bahreinas', 'Bangladešas', 'Barbadosas', 'Baltarusija',
    'Belgija', 'Belizas', 'Beninas', 'Butanas', 'Bolivija', 'Bosnija ir Hercegovina', 'Botsvana', 'Brazilija',
    'Brunėjus', 'Bulgarija', 'Burkina Fasas', 'Burundis', 'Čadas', 'Čilė', 'Kinija', 'Kolumbija', 'Komorai',
    'Kongas', 'Kosta Rika', 'Kroatija', 'Kuba', 'Kipras', 'Čekija', 'Danija', 'Džibutis', 'Dominika',
    'Dominikos Respublika', 'Ekvadoras', 'Egiptas', 'Salvadoras', 'Pusiaujo Gvinėja', 'Eritrėja', 'Estija',
    'Esvatinis', 'Etiopija', 'Fidžis', 'Suomija', 'Prancūzija', 'Gabonas', 'Gambija', 'Gruzija', 'Vokietija',
    'Gana', 'Graikija', 'Grenada', 'Gvatemala', 'Gvinėja', 'Gvinėja Bisau', 'Gajana', 'Haitis', 'Hondūras',
    'Vengrija', 'Islandija', 'Indija', 'Indonezija', 'Iranas', 'Irakas', 'Airija', 'Izraelis', 'Italija',
    'Jamaika', 'Japonija', 'Jordanija', 'Kazachstanas', 'Kenija', 'Kiribatis', 'Kuveitas',
    'Kirgizija', 'Laosas', 'Latvija', 'Libanas', 'Lesotas', 'Liberija', 'Libija', 'Lichtenšteinas', 'Lietuva',
    'Liuksemburgas', 'Madagaskaras', 'Malavis', 'Malaizija', 'Maldyvai', 'Malis', 'Malta', 'Maršalo Salos',
    'Mauritanija', 'Mauricijus', 'Meksika', 'Mikronezija', 'Moldova', 'Monakas', 'Mongolija', 'Juodkalnija',
    'Marokas', 'Mozambikas', 'Mianmaras', 'Namibija', 'Nauru', 'Nepalas', 'Nyderlandai', 'Naujoji Zelandija',
    'Nikaragva', 'Nigeris', 'Nigerija', 'Šiaurės Makedonija', 'Norvegija', 'Omanas', 'Pakistanas', 'Palau',
    'Palestina', 'Panama', 'Papua Naujoji Gvinėja', 'Paragvajus', 'Peru', 'Filipinai', 'Lenkija', 'Portugalija',
    'Kataras', 'Rumunija', 'Rusija', 'Ruanda', 'Sent Kitsas ir Nevis', 'Sent Lusija', 'Sent Vincentas ir Grenadinai',
    'Samoa', 'San Marinas', 'San Tomė ir Prinsipė', 'Saudo Arabija', 'Senegalas', 'Serbija', 'Seišeliai',
    'Siera Leonė', 'Singapūras', 'Slovakija', 'Slovėnija', 'Saliamono Salos', 'Somalis', 'PAR', 'Pietų Sudanas',
    'Ispanija', 'Šri Lanka', 'Sudanas', 'Surinamas', 'Švedija', 'Šveicarija', 'Sirija', 'Taivanas', 'Tadžikistanas',
    'Tanzanija', 'Tailandas', 'Timoras-Leste', 'Togas', 'Tonga', 'Trinidadas ir Tobagas', 'Tunisas', 'Turkija',
    'Turkmėnistanas', 'Tuvalu', 'Uganda', 'Ukraina', 'JAE', 'Jungtinė Karalystė', 'JAV', 'Urugvajus',
    'Uzbekistanas', 'Vanuatu', 'Venesuela', 'Vietnamas', 'Jemenas', 'Zambija', 'Zimbabvė',     'Korėja', 'Šiaurės Korėja',
    'Kambodža', 'Kamerūnas', 'Centrinės Afrikos Respublika', 'Demokratinė Kongo Respublika', 'Gvadelupa',
    'Honkongas', 'Makao', 'Puerto Rikas', 'Grenlandija', 'Farerų Salos', 'Gibraltaras', 'Monseratas',
}
